// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockEntityData {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub type_id: u32,
    pub type_name: String,
    pub block_state_id: u32,
    pub nbt: Vec<u8>,
    pub nbt_json: String,
    pub computer_id: Option<i32>,
    pub label: Option<String>,
    pub fuel: Option<i32>,
    pub on: Option<bool>,
    pub left_upgrade: Option<String>,
    pub right_upgrade: Option<String>,
}

impl __sdk::InModule for BlockEntityData {
    type Module = super::RemoteModule;
}
