// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockEntity {
    pub key: i64,
    pub chunk_key: i64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub type_id: u32,
    pub type_name: String,
    pub block_state_id: u32,
    pub nbt: Vec<u8>,
    pub nbt_json: String,
    pub computer_id: Option<i32>,
    pub label: Option<String>,
    pub fuel: Option<i32>,
    pub on: Option<bool>,
    pub left_upgrade: Option<String>,
    pub right_upgrade: Option<String>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for BlockEntity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BlockEntity`.
///
/// Provides typed access to columns for query building.
pub struct BlockEntityCols {
    pub key: __sdk::__query_builder::Col<BlockEntity, i64>,
    pub chunk_key: __sdk::__query_builder::Col<BlockEntity, i64>,
    pub x: __sdk::__query_builder::Col<BlockEntity, i32>,
    pub y: __sdk::__query_builder::Col<BlockEntity, i32>,
    pub z: __sdk::__query_builder::Col<BlockEntity, i32>,
    pub type_id: __sdk::__query_builder::Col<BlockEntity, u32>,
    pub type_name: __sdk::__query_builder::Col<BlockEntity, String>,
    pub block_state_id: __sdk::__query_builder::Col<BlockEntity, u32>,
    pub nbt: __sdk::__query_builder::Col<BlockEntity, Vec<u8>>,
    pub nbt_json: __sdk::__query_builder::Col<BlockEntity, String>,
    pub computer_id: __sdk::__query_builder::Col<BlockEntity, Option<i32>>,
    pub label: __sdk::__query_builder::Col<BlockEntity, Option<String>>,
    pub fuel: __sdk::__query_builder::Col<BlockEntity, Option<i32>>,
    pub on: __sdk::__query_builder::Col<BlockEntity, Option<bool>>,
    pub left_upgrade: __sdk::__query_builder::Col<BlockEntity, Option<String>>,
    pub right_upgrade: __sdk::__query_builder::Col<BlockEntity, Option<String>>,
    pub updated_at: __sdk::__query_builder::Col<BlockEntity, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BlockEntity {
    type Cols = BlockEntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BlockEntityCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            type_id: __sdk::__query_builder::Col::new(table_name, "type_id"),
            type_name: __sdk::__query_builder::Col::new(table_name, "type_name"),
            block_state_id: __sdk::__query_builder::Col::new(table_name, "block_state_id"),
            nbt: __sdk::__query_builder::Col::new(table_name, "nbt"),
            nbt_json: __sdk::__query_builder::Col::new(table_name, "nbt_json"),
            computer_id: __sdk::__query_builder::Col::new(table_name, "computer_id"),
            label: __sdk::__query_builder::Col::new(table_name, "label"),
            fuel: __sdk::__query_builder::Col::new(table_name, "fuel"),
            on: __sdk::__query_builder::Col::new(table_name, "on"),
            left_upgrade: __sdk::__query_builder::Col::new(table_name, "left_upgrade"),
            right_upgrade: __sdk::__query_builder::Col::new(table_name, "right_upgrade"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BlockEntity`.
///
/// Provides typed access to indexed columns for query building.
pub struct BlockEntityIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<BlockEntity, i64>,
    pub computer_id: __sdk::__query_builder::IxCol<BlockEntity, Option<i32>>,
    pub key: __sdk::__query_builder::IxCol<BlockEntity, i64>,
    pub type_name: __sdk::__query_builder::IxCol<BlockEntity, String>,
}

impl __sdk::__query_builder::HasIxCols for BlockEntity {
    type IxCols = BlockEntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BlockEntityIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
            computer_id: __sdk::__query_builder::IxCol::new(table_name, "computer_id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            type_name: __sdk::__query_builder::IxCol::new(table_name, "type_name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BlockEntity {}
