// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockChange {
    pub seq: u64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub old_state_id: u32,
    pub new_state_id: u32,
    pub at: __sdk::Timestamp,
}

impl __sdk::InModule for BlockChange {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BlockChange`.
///
/// Provides typed access to columns for query building.
pub struct BlockChangeCols {
    pub seq: __sdk::__query_builder::Col<BlockChange, u64>,
    pub x: __sdk::__query_builder::Col<BlockChange, i32>,
    pub y: __sdk::__query_builder::Col<BlockChange, i32>,
    pub z: __sdk::__query_builder::Col<BlockChange, i32>,
    pub old_state_id: __sdk::__query_builder::Col<BlockChange, u32>,
    pub new_state_id: __sdk::__query_builder::Col<BlockChange, u32>,
    pub at: __sdk::__query_builder::Col<BlockChange, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BlockChange {
    type Cols = BlockChangeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BlockChangeCols {
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            old_state_id: __sdk::__query_builder::Col::new(table_name, "old_state_id"),
            new_state_id: __sdk::__query_builder::Col::new(table_name, "new_state_id"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
        }
    }
}

/// Indexed column accessor struct for the table `BlockChange`.
///
/// Provides typed access to indexed columns for query building.
pub struct BlockChangeIxCols {
    pub seq: __sdk::__query_builder::IxCol<BlockChange, u64>,
}

impl __sdk::__query_builder::HasIxCols for BlockChange {
    type IxCols = BlockChangeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BlockChangeIxCols {
            seq: __sdk::__query_builder::IxCol::new(table_name, "seq"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BlockChange {}
