// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::block_state_row_type::BlockStateRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `block_state`.
///
/// Obtain a handle from the [`BlockStateTableAccess::block_state`] method on [`super::RemoteTables`],
/// like `ctx.db.block_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.block_state().on_insert(...)`.
pub struct BlockStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<BlockStateRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `block_state`.
pub struct BlockStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BlockStateTableAccessor {
    type Row = BlockStateRow;
    type Handle<'db> = BlockStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.block_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `block_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BlockStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BlockStateTableHandle`], which mediates access to the table `block_state`.
    fn block_state(&self) -> BlockStateTableHandle<'_>;
}

impl BlockStateTableAccess for super::RemoteTables {
    fn block_state(&self) -> BlockStateTableHandle<'_> {
        BlockStateTableHandle {
            imp: self.imp.get_table::<BlockStateRow>("block_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BlockStateInsertCallbackId(__sdk::CallbackId);
pub struct BlockStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BlockStateTableHandle<'ctx> {
    type Row = BlockStateRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BlockStateRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BlockStateTableHandle<'ctx> {
    type Row = BlockStateRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BlockStateRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BlockStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockStateInsertCallbackId {
        BlockStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BlockStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BlockStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockStateDeleteCallbackId {
        BlockStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BlockStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BlockStateTableHandle<'ctx> {
    type InsertCallbackId = BlockStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockStateInsertCallbackId {
        BlockStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BlockStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BlockStateTableHandle<'ctx> {
    type DeleteCallbackId = BlockStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockStateDeleteCallbackId {
        BlockStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BlockStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BlockStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BlockStateTableHandle<'ctx> {
    type UpdateCallbackId = BlockStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BlockStateUpdateCallbackId {
        BlockStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BlockStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BlockStateTableHandle<'ctx> {
    type UpdateCallbackId = BlockStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BlockStateUpdateCallbackId {
        BlockStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BlockStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `block_state`,
/// which allows point queries on the field of the same name
/// via the [`BlockStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.block_state().id().find(...)`.
pub struct BlockStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BlockStateRow, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BlockStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `block_state`.
    pub fn id(&self) -> BlockStateIdUnique<'ctx> {
        BlockStateIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BlockStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<BlockStateRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BlockStateRow>("block_state");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BlockStateRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BlockStateRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BlockStateRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait block_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BlockStateRow`.
    fn block_state(&self) -> __sdk::__query_builder::Table<BlockStateRow>;
}

impl block_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn block_state(&self) -> __sdk::__query_builder::Table<BlockStateRow> {
        __sdk::__query_builder::Table::new("block_state")
    }
}
