// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockStateRow {
    pub id: u32,
    pub name: String,
    pub properties: String,
}

impl __sdk::InModule for BlockStateRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BlockStateRow`.
///
/// Provides typed access to columns for query building.
pub struct BlockStateRowCols {
    pub id: __sdk::__query_builder::Col<BlockStateRow, u32>,
    pub name: __sdk::__query_builder::Col<BlockStateRow, String>,
    pub properties: __sdk::__query_builder::Col<BlockStateRow, String>,
}

impl __sdk::__query_builder::HasCols for BlockStateRow {
    type Cols = BlockStateRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BlockStateRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            properties: __sdk::__query_builder::Col::new(table_name, "properties"),
        }
    }
}

/// Indexed column accessor struct for the table `BlockStateRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct BlockStateRowIxCols {
    pub id: __sdk::__query_builder::IxCol<BlockStateRow, u32>,
    pub name: __sdk::__query_builder::IxCol<BlockStateRow, String>,
}

impl __sdk::__query_builder::HasIxCols for BlockStateRow {
    type IxCols = BlockStateRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BlockStateRowIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BlockStateRow {}
