// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockChangeData {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub old_state_id: u32,
    pub new_state_id: u32,
}

impl __sdk::InModule for BlockChangeData {
    type Module = super::RemoteModule;
}
