// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::block_entity_type::BlockEntity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `block_entity`.
///
/// Obtain a handle from the [`BlockEntityTableAccess::block_entity`] method on [`super::RemoteTables`],
/// like `ctx.db.block_entity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.block_entity().on_insert(...)`.
pub struct BlockEntityTableHandle<'ctx> {
    imp: __sdk::TableHandle<BlockEntity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `block_entity`.
pub struct BlockEntityTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BlockEntityTableAccessor {
    type Row = BlockEntity;
    type Handle<'db> = BlockEntityTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.block_entity()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `block_entity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BlockEntityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BlockEntityTableHandle`], which mediates access to the table `block_entity`.
    fn block_entity(&self) -> BlockEntityTableHandle<'_>;
}

impl BlockEntityTableAccess for super::RemoteTables {
    fn block_entity(&self) -> BlockEntityTableHandle<'_> {
        BlockEntityTableHandle {
            imp: self.imp.get_table::<BlockEntity>("block_entity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BlockEntityInsertCallbackId(__sdk::CallbackId);
pub struct BlockEntityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BlockEntityTableHandle<'ctx> {
    type Row = BlockEntity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BlockEntity> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BlockEntityTableHandle<'ctx> {
    type Row = BlockEntity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BlockEntity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BlockEntityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockEntityInsertCallbackId {
        BlockEntityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BlockEntityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BlockEntityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockEntityDeleteCallbackId {
        BlockEntityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BlockEntityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BlockEntityTableHandle<'ctx> {
    type InsertCallbackId = BlockEntityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockEntityInsertCallbackId {
        BlockEntityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BlockEntityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BlockEntityTableHandle<'ctx> {
    type DeleteCallbackId = BlockEntityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockEntityDeleteCallbackId {
        BlockEntityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BlockEntityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BlockEntityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BlockEntityTableHandle<'ctx> {
    type UpdateCallbackId = BlockEntityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BlockEntityUpdateCallbackId {
        BlockEntityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BlockEntityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BlockEntityTableHandle<'ctx> {
    type UpdateCallbackId = BlockEntityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BlockEntityUpdateCallbackId {
        BlockEntityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BlockEntityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `block_entity`,
/// which allows point queries on the field of the same name
/// via the [`BlockEntityKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.block_entity().key().find(...)`.
pub struct BlockEntityKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BlockEntity, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BlockEntityTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `block_entity`.
    pub fn key(&self) -> BlockEntityKeyUnique<'ctx> {
        BlockEntityKeyUnique {
            imp: self.imp.get_unique_constraint::<i64>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BlockEntityKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<BlockEntity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BlockEntity>("block_entity");
    _table.add_unique_constraint::<i64>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BlockEntity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BlockEntity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BlockEntity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait block_entityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BlockEntity`.
    fn block_entity(&self) -> __sdk::__query_builder::Table<BlockEntity>;
}

impl block_entityQueryTableAccess for __sdk::QueryTableAccessor {
    fn block_entity(&self) -> __sdk::__query_builder::Table<BlockEntity> {
        __sdk::__query_builder::Table::new("block_entity")
    }
}
