// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::block_change_type::BlockChange;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `block_change`.
///
/// Obtain a handle from the [`BlockChangeTableAccess::block_change`] method on [`super::RemoteTables`],
/// like `ctx.db.block_change()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.block_change().on_insert(...)`.
pub struct BlockChangeTableHandle<'ctx> {
    imp: __sdk::TableHandle<BlockChange>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `block_change`.
pub struct BlockChangeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BlockChangeTableAccessor {
    type Row = BlockChange;
    type Handle<'db> = BlockChangeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.block_change()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `block_change`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BlockChangeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BlockChangeTableHandle`], which mediates access to the table `block_change`.
    fn block_change(&self) -> BlockChangeTableHandle<'_>;
}

impl BlockChangeTableAccess for super::RemoteTables {
    fn block_change(&self) -> BlockChangeTableHandle<'_> {
        BlockChangeTableHandle {
            imp: self.imp.get_table::<BlockChange>("block_change"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BlockChangeInsertCallbackId(__sdk::CallbackId);
pub struct BlockChangeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BlockChangeTableHandle<'ctx> {
    type Row = BlockChange;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BlockChange> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BlockChangeTableHandle<'ctx> {
    type Row = BlockChange;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BlockChange> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BlockChangeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockChangeInsertCallbackId {
        BlockChangeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BlockChangeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BlockChangeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockChangeDeleteCallbackId {
        BlockChangeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BlockChangeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BlockChangeTableHandle<'ctx> {
    type InsertCallbackId = BlockChangeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockChangeInsertCallbackId {
        BlockChangeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BlockChangeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BlockChangeTableHandle<'ctx> {
    type DeleteCallbackId = BlockChangeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockChangeDeleteCallbackId {
        BlockChangeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BlockChangeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BlockChangeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BlockChangeTableHandle<'ctx> {
    type UpdateCallbackId = BlockChangeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BlockChangeUpdateCallbackId {
        BlockChangeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BlockChangeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BlockChangeTableHandle<'ctx> {
    type UpdateCallbackId = BlockChangeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BlockChangeUpdateCallbackId {
        BlockChangeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BlockChangeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `seq` unique index on the table `block_change`,
/// which allows point queries on the field of the same name
/// via the [`BlockChangeSeqUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.block_change().seq().find(...)`.
pub struct BlockChangeSeqUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BlockChange, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BlockChangeTableHandle<'ctx> {
    /// Get a handle on the `seq` unique index on the table `block_change`.
    pub fn seq(&self) -> BlockChangeSeqUnique<'ctx> {
        BlockChangeSeqUnique {
            imp: self.imp.get_unique_constraint::<u64>("seq"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BlockChangeSeqUnique<'ctx> {
    /// Find the subscribed row whose `seq` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BlockChange> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BlockChange>("block_change");
    _table.add_unique_constraint::<u64>("seq", |row| &row.seq);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BlockChange>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BlockChange>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BlockChange`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait block_changeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BlockChange`.
    fn block_change(&self) -> __sdk::__query_builder::Table<BlockChange>;
}

impl block_changeQueryTableAccess for __sdk::QueryTableAccessor {
    fn block_change(&self) -> __sdk::__query_builder::Table<BlockChange> {
        __sdk::__query_builder::Table::new("block_change")
    }
}
