// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bot_status_type::BotStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `bot_status`.
///
/// Obtain a handle from the [`BotStatusTableAccess::bot_status`] method on [`super::RemoteTables`],
/// like `ctx.db.bot_status()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bot_status().on_insert(...)`.
pub struct BotStatusTableHandle<'ctx> {
    imp: __sdk::TableHandle<BotStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `bot_status`.
pub struct BotStatusTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BotStatusTableAccessor {
    type Row = BotStatus;
    type Handle<'db> = BotStatusTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.bot_status()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `bot_status`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BotStatusTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BotStatusTableHandle`], which mediates access to the table `bot_status`.
    fn bot_status(&self) -> BotStatusTableHandle<'_>;
}

impl BotStatusTableAccess for super::RemoteTables {
    fn bot_status(&self) -> BotStatusTableHandle<'_> {
        BotStatusTableHandle {
            imp: self.imp.get_table::<BotStatus>("bot_status"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BotStatusInsertCallbackId(__sdk::CallbackId);
pub struct BotStatusDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BotStatusTableHandle<'ctx> {
    type Row = BotStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BotStatus> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BotStatusTableHandle<'ctx> {
    type Row = BotStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BotStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BotStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotStatusInsertCallbackId {
        BotStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BotStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BotStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotStatusDeleteCallbackId {
        BotStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BotStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BotStatusTableHandle<'ctx> {
    type InsertCallbackId = BotStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotStatusInsertCallbackId {
        BotStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BotStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BotStatusTableHandle<'ctx> {
    type DeleteCallbackId = BotStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotStatusDeleteCallbackId {
        BotStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BotStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BotStatusUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BotStatusTableHandle<'ctx> {
    type UpdateCallbackId = BotStatusUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BotStatusUpdateCallbackId {
        BotStatusUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BotStatusUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BotStatusTableHandle<'ctx> {
    type UpdateCallbackId = BotStatusUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BotStatusUpdateCallbackId {
        BotStatusUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BotStatusUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `bot_status`,
/// which allows point queries on the field of the same name
/// via the [`BotStatusIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bot_status().id().find(...)`.
pub struct BotStatusIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BotStatus, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BotStatusTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `bot_status`.
    pub fn id(&self) -> BotStatusIdUnique<'ctx> {
        BotStatusIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BotStatusIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<BotStatus> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BotStatus>("bot_status");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BotStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BotStatus>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BotStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait bot_statusQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BotStatus`.
    fn bot_status(&self) -> __sdk::__query_builder::Table<BotStatus>;
}

impl bot_statusQueryTableAccess for __sdk::QueryTableAccessor {
    fn bot_status(&self) -> __sdk::__query_builder::Table<BotStatus> {
        __sdk::__query_builder::Table::new("bot_status")
    }
}
