// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bot_command_type::BotCommand;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `bot_command`.
///
/// Obtain a handle from the [`BotCommandTableAccess::bot_command`] method on [`super::RemoteTables`],
/// like `ctx.db.bot_command()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bot_command().on_insert(...)`.
pub struct BotCommandTableHandle<'ctx> {
    imp: __sdk::TableHandle<BotCommand>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `bot_command`.
pub struct BotCommandTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BotCommandTableAccessor {
    type Row = BotCommand;
    type Handle<'db> = BotCommandTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.bot_command()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `bot_command`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BotCommandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BotCommandTableHandle`], which mediates access to the table `bot_command`.
    fn bot_command(&self) -> BotCommandTableHandle<'_>;
}

impl BotCommandTableAccess for super::RemoteTables {
    fn bot_command(&self) -> BotCommandTableHandle<'_> {
        BotCommandTableHandle {
            imp: self.imp.get_table::<BotCommand>("bot_command"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BotCommandInsertCallbackId(__sdk::CallbackId);
pub struct BotCommandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BotCommandTableHandle<'ctx> {
    type Row = BotCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BotCommand> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BotCommandTableHandle<'ctx> {
    type Row = BotCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BotCommand> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BotCommandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotCommandInsertCallbackId {
        BotCommandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BotCommandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BotCommandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotCommandDeleteCallbackId {
        BotCommandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BotCommandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BotCommandTableHandle<'ctx> {
    type InsertCallbackId = BotCommandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotCommandInsertCallbackId {
        BotCommandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BotCommandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BotCommandTableHandle<'ctx> {
    type DeleteCallbackId = BotCommandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotCommandDeleteCallbackId {
        BotCommandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BotCommandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BotCommandUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BotCommandTableHandle<'ctx> {
    type UpdateCallbackId = BotCommandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BotCommandUpdateCallbackId {
        BotCommandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BotCommandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BotCommandTableHandle<'ctx> {
    type UpdateCallbackId = BotCommandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BotCommandUpdateCallbackId {
        BotCommandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BotCommandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `bot_command`,
/// which allows point queries on the field of the same name
/// via the [`BotCommandIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bot_command().id().find(...)`.
pub struct BotCommandIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BotCommand, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BotCommandTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `bot_command`.
    pub fn id(&self) -> BotCommandIdUnique<'ctx> {
        BotCommandIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BotCommandIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BotCommand> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BotCommand>("bot_command");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BotCommand>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BotCommand>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BotCommand`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait bot_commandQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BotCommand`.
    fn bot_command(&self) -> __sdk::__query_builder::Table<BotCommand>;
}

impl bot_commandQueryTableAccess for __sdk::QueryTableAccessor {
    fn bot_command(&self) -> __sdk::__query_builder::Table<BotCommand> {
        __sdk::__query_builder::Table::new("bot_command")
    }
}
