// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BotStatus {
    pub id: u32,
    pub server_addr: String,
    pub username: String,
    pub state: String,
    pub detail: String,
    pub dimension: String,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub view_distance: i32,
    pub chunks_loaded: u32,
    pub packets_seen: u64,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for BotStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BotStatus`.
///
/// Provides typed access to columns for query building.
pub struct BotStatusCols {
    pub id: __sdk::__query_builder::Col<BotStatus, u32>,
    pub server_addr: __sdk::__query_builder::Col<BotStatus, String>,
    pub username: __sdk::__query_builder::Col<BotStatus, String>,
    pub state: __sdk::__query_builder::Col<BotStatus, String>,
    pub detail: __sdk::__query_builder::Col<BotStatus, String>,
    pub dimension: __sdk::__query_builder::Col<BotStatus, String>,
    pub x: __sdk::__query_builder::Col<BotStatus, f64>,
    pub y: __sdk::__query_builder::Col<BotStatus, f64>,
    pub z: __sdk::__query_builder::Col<BotStatus, f64>,
    pub view_distance: __sdk::__query_builder::Col<BotStatus, i32>,
    pub chunks_loaded: __sdk::__query_builder::Col<BotStatus, u32>,
    pub packets_seen: __sdk::__query_builder::Col<BotStatus, u64>,
    pub updated_at: __sdk::__query_builder::Col<BotStatus, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BotStatus {
    type Cols = BotStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BotStatusCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            server_addr: __sdk::__query_builder::Col::new(table_name, "server_addr"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            detail: __sdk::__query_builder::Col::new(table_name, "detail"),
            dimension: __sdk::__query_builder::Col::new(table_name, "dimension"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            view_distance: __sdk::__query_builder::Col::new(table_name, "view_distance"),
            chunks_loaded: __sdk::__query_builder::Col::new(table_name, "chunks_loaded"),
            packets_seen: __sdk::__query_builder::Col::new(table_name, "packets_seen"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BotStatus`.
///
/// Provides typed access to indexed columns for query building.
pub struct BotStatusIxCols {
    pub id: __sdk::__query_builder::IxCol<BotStatus, u32>,
}

impl __sdk::__query_builder::HasIxCols for BotStatus {
    type IxCols = BotStatusIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BotStatusIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BotStatus {}
