// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BotCommand {
    pub id: u64,
    pub kind: String,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub face: String,
    pub status: String,
    pub detail: String,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
    pub window_id: i32,
    pub slot: i32,
    pub button: i32,
    pub mode: i32,
    pub slots: String,
}

impl __sdk::InModule for BotCommand {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BotCommand`.
///
/// Provides typed access to columns for query building.
pub struct BotCommandCols {
    pub id: __sdk::__query_builder::Col<BotCommand, u64>,
    pub kind: __sdk::__query_builder::Col<BotCommand, String>,
    pub x: __sdk::__query_builder::Col<BotCommand, i32>,
    pub y: __sdk::__query_builder::Col<BotCommand, i32>,
    pub z: __sdk::__query_builder::Col<BotCommand, i32>,
    pub face: __sdk::__query_builder::Col<BotCommand, String>,
    pub status: __sdk::__query_builder::Col<BotCommand, String>,
    pub detail: __sdk::__query_builder::Col<BotCommand, String>,
    pub created_at: __sdk::__query_builder::Col<BotCommand, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<BotCommand, __sdk::Timestamp>,
    pub window_id: __sdk::__query_builder::Col<BotCommand, i32>,
    pub slot: __sdk::__query_builder::Col<BotCommand, i32>,
    pub button: __sdk::__query_builder::Col<BotCommand, i32>,
    pub mode: __sdk::__query_builder::Col<BotCommand, i32>,
    pub slots: __sdk::__query_builder::Col<BotCommand, String>,
}

impl __sdk::__query_builder::HasCols for BotCommand {
    type Cols = BotCommandCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BotCommandCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            face: __sdk::__query_builder::Col::new(table_name, "face"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            detail: __sdk::__query_builder::Col::new(table_name, "detail"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            window_id: __sdk::__query_builder::Col::new(table_name, "window_id"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
            button: __sdk::__query_builder::Col::new(table_name, "button"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
        }
    }
}

/// Indexed column accessor struct for the table `BotCommand`.
///
/// Provides typed access to indexed columns for query building.
pub struct BotCommandIxCols {
    pub id: __sdk::__query_builder::IxCol<BotCommand, u64>,
    pub status: __sdk::__query_builder::IxCol<BotCommand, String>,
}

impl __sdk::__query_builder::HasIxCols for BotCommand {
    type IxCols = BotCommandIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BotCommandIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BotCommand {}
