// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chunk_type::Chunk;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk`.
///
/// Obtain a handle from the [`ChunkTableAccess::chunk`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk().on_insert(...)`.
pub struct ChunkTableHandle<'ctx> {
    imp: __sdk::TableHandle<Chunk>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `chunk`.
pub struct ChunkTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ChunkTableAccessor {
    type Row = Chunk;
    type Handle<'db> = ChunkTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.chunk()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkTableHandle`], which mediates access to the table `chunk`.
    fn chunk(&self) -> ChunkTableHandle<'_>;
}

impl ChunkTableAccess for super::RemoteTables {
    fn chunk(&self) -> ChunkTableHandle<'_> {
        ChunkTableHandle {
            imp: self.imp.get_table::<Chunk>("chunk"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkInsertCallbackId(__sdk::CallbackId);
pub struct ChunkDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ChunkTableHandle<'ctx> {
    type Row = Chunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Chunk> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ChunkTableHandle<'ctx> {
    type Row = Chunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Chunk> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkInsertCallbackId {
        ChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkDeleteCallbackId {
        ChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ChunkTableHandle<'ctx> {
    type InsertCallbackId = ChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkInsertCallbackId {
        ChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ChunkTableHandle<'ctx> {
    type DeleteCallbackId = ChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkDeleteCallbackId {
        ChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChunkUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChunkTableHandle<'ctx> {
    type UpdateCallbackId = ChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkUpdateCallbackId {
        ChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ChunkTableHandle<'ctx> {
    type UpdateCallbackId = ChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkUpdateCallbackId {
        ChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `chunk`,
/// which allows point queries on the field of the same name
/// via the [`ChunkKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk().key().find(...)`.
pub struct ChunkKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Chunk, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChunkTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `chunk`.
    pub fn key(&self) -> ChunkKeyUnique<'ctx> {
        ChunkKeyUnique {
            imp: self.imp.get_unique_constraint::<i64>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChunkKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<Chunk> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Chunk>("chunk");
    _table.add_unique_constraint::<i64>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Chunk>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Chunk>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Chunk`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait chunkQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Chunk`.
    fn chunk(&self) -> __sdk::__query_builder::Table<Chunk>;
}

impl chunkQueryTableAccess for __sdk::QueryTableAccessor {
    fn chunk(&self) -> __sdk::__query_builder::Table<Chunk> {
        __sdk::__query_builder::Table::new("chunk")
    }
}
