// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chunk_light_type::ChunkLight;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk_light`.
///
/// Obtain a handle from the [`ChunkLightTableAccess::chunk_light`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk_light()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_light().on_insert(...)`.
pub struct ChunkLightTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChunkLight>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `chunk_light`.
pub struct ChunkLightTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ChunkLightTableAccessor {
    type Row = ChunkLight;
    type Handle<'db> = ChunkLightTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.chunk_light()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk_light`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkLightTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkLightTableHandle`], which mediates access to the table `chunk_light`.
    fn chunk_light(&self) -> ChunkLightTableHandle<'_>;
}

impl ChunkLightTableAccess for super::RemoteTables {
    fn chunk_light(&self) -> ChunkLightTableHandle<'_> {
        ChunkLightTableHandle {
            imp: self.imp.get_table::<ChunkLight>("chunk_light"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkLightInsertCallbackId(__sdk::CallbackId);
pub struct ChunkLightDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ChunkLightTableHandle<'ctx> {
    type Row = ChunkLight;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkLight> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ChunkLightTableHandle<'ctx> {
    type Row = ChunkLight;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkLight> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkLightInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkLightInsertCallbackId {
        ChunkLightInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkLightInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkLightDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkLightDeleteCallbackId {
        ChunkLightDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkLightDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ChunkLightTableHandle<'ctx> {
    type InsertCallbackId = ChunkLightInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkLightInsertCallbackId {
        ChunkLightInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkLightInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ChunkLightTableHandle<'ctx> {
    type DeleteCallbackId = ChunkLightDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkLightDeleteCallbackId {
        ChunkLightDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkLightDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChunkLightUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChunkLightTableHandle<'ctx> {
    type UpdateCallbackId = ChunkLightUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkLightUpdateCallbackId {
        ChunkLightUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkLightUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ChunkLightTableHandle<'ctx> {
    type UpdateCallbackId = ChunkLightUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkLightUpdateCallbackId {
        ChunkLightUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkLightUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `chunk_light`,
/// which allows point queries on the field of the same name
/// via the [`ChunkLightKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_light().key().find(...)`.
pub struct ChunkLightKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChunkLight, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChunkLightTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `chunk_light`.
    pub fn key(&self) -> ChunkLightKeyUnique<'ctx> {
        ChunkLightKeyUnique {
            imp: self.imp.get_unique_constraint::<i64>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChunkLightKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<ChunkLight> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChunkLight>("chunk_light");
    _table.add_unique_constraint::<i64>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChunkLight>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChunkLight>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChunkLight`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait chunk_lightQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChunkLight`.
    fn chunk_light(&self) -> __sdk::__query_builder::Table<ChunkLight>;
}

impl chunk_lightQueryTableAccess for __sdk::QueryTableAccessor {
    fn chunk_light(&self) -> __sdk::__query_builder::Table<ChunkLight> {
        __sdk::__query_builder::Table::new("chunk_light")
    }
}
