// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChunkLight {
    pub key: i64,
    pub chunk_key: i64,
    pub cx: i32,
    pub cz: i32,
    pub sy: i32,
    pub sky_light: Vec<u8>,
    pub block_light: Vec<u8>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ChunkLight {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChunkLight`.
///
/// Provides typed access to columns for query building.
pub struct ChunkLightCols {
    pub key: __sdk::__query_builder::Col<ChunkLight, i64>,
    pub chunk_key: __sdk::__query_builder::Col<ChunkLight, i64>,
    pub cx: __sdk::__query_builder::Col<ChunkLight, i32>,
    pub cz: __sdk::__query_builder::Col<ChunkLight, i32>,
    pub sy: __sdk::__query_builder::Col<ChunkLight, i32>,
    pub sky_light: __sdk::__query_builder::Col<ChunkLight, Vec<u8>>,
    pub block_light: __sdk::__query_builder::Col<ChunkLight, Vec<u8>>,
    pub updated_at: __sdk::__query_builder::Col<ChunkLight, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ChunkLight {
    type Cols = ChunkLightCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChunkLightCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            cx: __sdk::__query_builder::Col::new(table_name, "cx"),
            cz: __sdk::__query_builder::Col::new(table_name, "cz"),
            sy: __sdk::__query_builder::Col::new(table_name, "sy"),
            sky_light: __sdk::__query_builder::Col::new(table_name, "sky_light"),
            block_light: __sdk::__query_builder::Col::new(table_name, "block_light"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ChunkLight`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChunkLightIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<ChunkLight, i64>,
    pub key: __sdk::__query_builder::IxCol<ChunkLight, i64>,
}

impl __sdk::__query_builder::HasIxCols for ChunkLight {
    type IxCols = ChunkLightIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChunkLightIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChunkLight {}
