// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChunkSection {
    pub key: i64,
    pub chunk_key: i64,
    pub cx: i32,
    pub cz: i32,
    pub sy: i32,
    pub non_air_count: u16,
    pub block_bits: u8,
    pub block_palette: Vec<u32>,
    pub block_data: Vec<u64>,
    pub biome_bits: u8,
    pub biome_palette: Vec<u32>,
    pub biome_data: Vec<u64>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ChunkSection {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChunkSection`.
///
/// Provides typed access to columns for query building.
pub struct ChunkSectionCols {
    pub key: __sdk::__query_builder::Col<ChunkSection, i64>,
    pub chunk_key: __sdk::__query_builder::Col<ChunkSection, i64>,
    pub cx: __sdk::__query_builder::Col<ChunkSection, i32>,
    pub cz: __sdk::__query_builder::Col<ChunkSection, i32>,
    pub sy: __sdk::__query_builder::Col<ChunkSection, i32>,
    pub non_air_count: __sdk::__query_builder::Col<ChunkSection, u16>,
    pub block_bits: __sdk::__query_builder::Col<ChunkSection, u8>,
    pub block_palette: __sdk::__query_builder::Col<ChunkSection, Vec<u32>>,
    pub block_data: __sdk::__query_builder::Col<ChunkSection, Vec<u64>>,
    pub biome_bits: __sdk::__query_builder::Col<ChunkSection, u8>,
    pub biome_palette: __sdk::__query_builder::Col<ChunkSection, Vec<u32>>,
    pub biome_data: __sdk::__query_builder::Col<ChunkSection, Vec<u64>>,
    pub updated_at: __sdk::__query_builder::Col<ChunkSection, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ChunkSection {
    type Cols = ChunkSectionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChunkSectionCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            cx: __sdk::__query_builder::Col::new(table_name, "cx"),
            cz: __sdk::__query_builder::Col::new(table_name, "cz"),
            sy: __sdk::__query_builder::Col::new(table_name, "sy"),
            non_air_count: __sdk::__query_builder::Col::new(table_name, "non_air_count"),
            block_bits: __sdk::__query_builder::Col::new(table_name, "block_bits"),
            block_palette: __sdk::__query_builder::Col::new(table_name, "block_palette"),
            block_data: __sdk::__query_builder::Col::new(table_name, "block_data"),
            biome_bits: __sdk::__query_builder::Col::new(table_name, "biome_bits"),
            biome_palette: __sdk::__query_builder::Col::new(table_name, "biome_palette"),
            biome_data: __sdk::__query_builder::Col::new(table_name, "biome_data"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ChunkSection`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChunkSectionIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<ChunkSection, i64>,
    pub key: __sdk::__query_builder::IxCol<ChunkSection, i64>,
}

impl __sdk::__query_builder::HasIxCols for ChunkSection {
    type IxCols = ChunkSectionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChunkSectionIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChunkSection {}
