// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Chunk {
    pub key: i64,
    pub dimension: String,
    pub cx: i32,
    pub cz: i32,
    pub min_section: i32,
    pub section_count: u32,
    pub loaded_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Chunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Chunk`.
///
/// Provides typed access to columns for query building.
pub struct ChunkCols {
    pub key: __sdk::__query_builder::Col<Chunk, i64>,
    pub dimension: __sdk::__query_builder::Col<Chunk, String>,
    pub cx: __sdk::__query_builder::Col<Chunk, i32>,
    pub cz: __sdk::__query_builder::Col<Chunk, i32>,
    pub min_section: __sdk::__query_builder::Col<Chunk, i32>,
    pub section_count: __sdk::__query_builder::Col<Chunk, u32>,
    pub loaded_at: __sdk::__query_builder::Col<Chunk, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Chunk, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Chunk {
    type Cols = ChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChunkCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            dimension: __sdk::__query_builder::Col::new(table_name, "dimension"),
            cx: __sdk::__query_builder::Col::new(table_name, "cx"),
            cz: __sdk::__query_builder::Col::new(table_name, "cz"),
            min_section: __sdk::__query_builder::Col::new(table_name, "min_section"),
            section_count: __sdk::__query_builder::Col::new(table_name, "section_count"),
            loaded_at: __sdk::__query_builder::Col::new(table_name, "loaded_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Chunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChunkIxCols {
    pub cx: __sdk::__query_builder::IxCol<Chunk, i32>,
    pub cz: __sdk::__query_builder::IxCol<Chunk, i32>,
    pub key: __sdk::__query_builder::IxCol<Chunk, i64>,
}

impl __sdk::__query_builder::HasIxCols for Chunk {
    type IxCols = ChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChunkIxCols {
            cx: __sdk::__query_builder::IxCol::new(table_name, "cx"),
            cz: __sdk::__query_builder::IxCol::new(table_name, "cz"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Chunk {}
