// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chunk_section_type::ChunkSection;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk_section`.
///
/// Obtain a handle from the [`ChunkSectionTableAccess::chunk_section`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk_section()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_section().on_insert(...)`.
pub struct ChunkSectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChunkSection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `chunk_section`.
pub struct ChunkSectionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ChunkSectionTableAccessor {
    type Row = ChunkSection;
    type Handle<'db> = ChunkSectionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.chunk_section()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk_section`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkSectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkSectionTableHandle`], which mediates access to the table `chunk_section`.
    fn chunk_section(&self) -> ChunkSectionTableHandle<'_>;
}

impl ChunkSectionTableAccess for super::RemoteTables {
    fn chunk_section(&self) -> ChunkSectionTableHandle<'_> {
        ChunkSectionTableHandle {
            imp: self.imp.get_table::<ChunkSection>("chunk_section"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkSectionInsertCallbackId(__sdk::CallbackId);
pub struct ChunkSectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ChunkSectionTableHandle<'ctx> {
    type Row = ChunkSection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkSection> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ChunkSectionTableHandle<'ctx> {
    type Row = ChunkSection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkSection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkSectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkSectionInsertCallbackId {
        ChunkSectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkSectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkSectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkSectionDeleteCallbackId {
        ChunkSectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkSectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ChunkSectionTableHandle<'ctx> {
    type InsertCallbackId = ChunkSectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkSectionInsertCallbackId {
        ChunkSectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkSectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ChunkSectionTableHandle<'ctx> {
    type DeleteCallbackId = ChunkSectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkSectionDeleteCallbackId {
        ChunkSectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkSectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChunkSectionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChunkSectionTableHandle<'ctx> {
    type UpdateCallbackId = ChunkSectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkSectionUpdateCallbackId {
        ChunkSectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkSectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ChunkSectionTableHandle<'ctx> {
    type UpdateCallbackId = ChunkSectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkSectionUpdateCallbackId {
        ChunkSectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkSectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `chunk_section`,
/// which allows point queries on the field of the same name
/// via the [`ChunkSectionKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_section().key().find(...)`.
pub struct ChunkSectionKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChunkSection, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChunkSectionTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `chunk_section`.
    pub fn key(&self) -> ChunkSectionKeyUnique<'ctx> {
        ChunkSectionKeyUnique {
            imp: self.imp.get_unique_constraint::<i64>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChunkSectionKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<ChunkSection> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChunkSection>("chunk_section");
    _table.add_unique_constraint::<i64>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChunkSection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChunkSection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChunkSection`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait chunk_sectionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChunkSection`.
    fn chunk_section(&self) -> __sdk::__query_builder::Table<ChunkSection>;
}

impl chunk_sectionQueryTableAccess for __sdk::QueryTableAccessor {
    fn chunk_section(&self) -> __sdk::__query_builder::Table<ChunkSection> {
        __sdk::__query_builder::Table::new("chunk_section")
    }
}
