// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CloseContainerArgs {
    pub window_id: i32,
}

impl From<CloseContainerArgs> for super::Reducer {
    fn from(args: CloseContainerArgs) -> Self {
        Self::CloseContainer {
            window_id: args.window_id,
        }
    }
}

impl __sdk::InModule for CloseContainerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `close_container`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait close_container {
    /// Request that the remote module invoke the reducer `close_container` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`close_container:close_container_then`] to run a callback after the reducer completes.
    fn close_container(&self, window_id: i32) -> __sdk::Result<()> {
        self.close_container_then(window_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `close_container` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn close_container_then(
        &self,
        window_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl close_container for super::RemoteReducers {
    fn close_container_then(
        &self,
        window_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CloseContainerArgs { window_id }, callback)
    }
}
