// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Container {
    pub window_id: i32,
    pub menu_type: String,
    pub title: String,
    pub opened_from_x: Option<i32>,
    pub opened_from_y: Option<i32>,
    pub opened_from_z: Option<i32>,
    pub slots: Vec<String>,
    pub carried: String,
    pub state_id: i32,
    pub undecoded_component: Option<String>,
    pub opened_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Container {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Container`.
///
/// Provides typed access to columns for query building.
pub struct ContainerCols {
    pub window_id: __sdk::__query_builder::Col<Container, i32>,
    pub menu_type: __sdk::__query_builder::Col<Container, String>,
    pub title: __sdk::__query_builder::Col<Container, String>,
    pub opened_from_x: __sdk::__query_builder::Col<Container, Option<i32>>,
    pub opened_from_y: __sdk::__query_builder::Col<Container, Option<i32>>,
    pub opened_from_z: __sdk::__query_builder::Col<Container, Option<i32>>,
    pub slots: __sdk::__query_builder::Col<Container, Vec<String>>,
    pub carried: __sdk::__query_builder::Col<Container, String>,
    pub state_id: __sdk::__query_builder::Col<Container, i32>,
    pub undecoded_component: __sdk::__query_builder::Col<Container, Option<String>>,
    pub opened_at: __sdk::__query_builder::Col<Container, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Container, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Container {
    type Cols = ContainerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContainerCols {
            window_id: __sdk::__query_builder::Col::new(table_name, "window_id"),
            menu_type: __sdk::__query_builder::Col::new(table_name, "menu_type"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            opened_from_x: __sdk::__query_builder::Col::new(table_name, "opened_from_x"),
            opened_from_y: __sdk::__query_builder::Col::new(table_name, "opened_from_y"),
            opened_from_z: __sdk::__query_builder::Col::new(table_name, "opened_from_z"),
            slots: __sdk::__query_builder::Col::new(table_name, "slots"),
            carried: __sdk::__query_builder::Col::new(table_name, "carried"),
            state_id: __sdk::__query_builder::Col::new(table_name, "state_id"),
            undecoded_component: __sdk::__query_builder::Col::new(
                table_name,
                "undecoded_component",
            ),
            opened_at: __sdk::__query_builder::Col::new(table_name, "opened_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Container`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContainerIxCols {
    pub window_id: __sdk::__query_builder::IxCol<Container, i32>,
}

impl __sdk::__query_builder::HasIxCols for Container {
    type IxCols = ContainerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContainerIxCols {
            window_id: __sdk::__query_builder::IxCol::new(table_name, "window_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Container {}
