// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContainerData {
    pub window_id: i32,
    pub menu_type: String,
    pub title: String,
    pub opened_from_x: Option<i32>,
    pub opened_from_y: Option<i32>,
    pub opened_from_z: Option<i32>,
    pub slots: Vec<String>,
    pub carried: String,
    pub state_id: i32,
    pub undecoded_component: Option<String>,
}

impl __sdk::InModule for ContainerData {
    type Module = super::RemoteModule;
}
