// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::container_type::Container;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `container`.
///
/// Obtain a handle from the [`ContainerTableAccess::container`] method on [`super::RemoteTables`],
/// like `ctx.db.container()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.container().on_insert(...)`.
pub struct ContainerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Container>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `container`.
pub struct ContainerTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ContainerTableAccessor {
    type Row = Container;
    type Handle<'db> = ContainerTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.container()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `container`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContainerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContainerTableHandle`], which mediates access to the table `container`.
    fn container(&self) -> ContainerTableHandle<'_>;
}

impl ContainerTableAccess for super::RemoteTables {
    fn container(&self) -> ContainerTableHandle<'_> {
        ContainerTableHandle {
            imp: self.imp.get_table::<Container>("container"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContainerInsertCallbackId(__sdk::CallbackId);
pub struct ContainerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ContainerTableHandle<'ctx> {
    type Row = Container;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Container> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ContainerTableHandle<'ctx> {
    type Row = Container;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Container> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContainerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainerInsertCallbackId {
        ContainerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContainerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContainerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainerDeleteCallbackId {
        ContainerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContainerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ContainerTableHandle<'ctx> {
    type InsertCallbackId = ContainerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainerInsertCallbackId {
        ContainerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContainerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ContainerTableHandle<'ctx> {
    type DeleteCallbackId = ContainerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainerDeleteCallbackId {
        ContainerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContainerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ContainerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ContainerTableHandle<'ctx> {
    type UpdateCallbackId = ContainerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContainerUpdateCallbackId {
        ContainerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContainerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ContainerTableHandle<'ctx> {
    type UpdateCallbackId = ContainerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContainerUpdateCallbackId {
        ContainerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContainerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `window_id` unique index on the table `container`,
/// which allows point queries on the field of the same name
/// via the [`ContainerWindowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.container().window_id().find(...)`.
pub struct ContainerWindowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Container, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContainerTableHandle<'ctx> {
    /// Get a handle on the `window_id` unique index on the table `container`.
    pub fn window_id(&self) -> ContainerWindowIdUnique<'ctx> {
        ContainerWindowIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("window_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContainerWindowIdUnique<'ctx> {
    /// Find the subscribed row whose `window_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<Container> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Container>("container");
    _table.add_unique_constraint::<i32>("window_id", |row| &row.window_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Container>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Container>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Container`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait containerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Container`.
    fn container(&self) -> __sdk::__query_builder::Table<Container>;
}

impl containerQueryTableAccess for __sdk::QueryTableAccessor {
    fn container(&self) -> __sdk::__query_builder::Table<Container> {
        __sdk::__query_builder::Table::new("container")
    }
}
