// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Entity {
    pub id: i32,
    pub uuid: String,
    pub type_id: u32,
    pub type_name: String,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub pitch: f32,
    pub head_yaw: f32,
    pub vx: f64,
    pub vy: f64,
    pub vz: f64,
    pub data: i32,
    pub custom_name: Option<String>,
    pub updated_at: __sdk::Timestamp,
    pub appearance: Option<String>,
    pub equipment: Option<String>,
}

impl __sdk::InModule for Entity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Entity`.
///
/// Provides typed access to columns for query building.
pub struct EntityCols {
    pub id: __sdk::__query_builder::Col<Entity, i32>,
    pub uuid: __sdk::__query_builder::Col<Entity, String>,
    pub type_id: __sdk::__query_builder::Col<Entity, u32>,
    pub type_name: __sdk::__query_builder::Col<Entity, String>,
    pub x: __sdk::__query_builder::Col<Entity, f64>,
    pub y: __sdk::__query_builder::Col<Entity, f64>,
    pub z: __sdk::__query_builder::Col<Entity, f64>,
    pub yaw: __sdk::__query_builder::Col<Entity, f32>,
    pub pitch: __sdk::__query_builder::Col<Entity, f32>,
    pub head_yaw: __sdk::__query_builder::Col<Entity, f32>,
    pub vx: __sdk::__query_builder::Col<Entity, f64>,
    pub vy: __sdk::__query_builder::Col<Entity, f64>,
    pub vz: __sdk::__query_builder::Col<Entity, f64>,
    pub data: __sdk::__query_builder::Col<Entity, i32>,
    pub custom_name: __sdk::__query_builder::Col<Entity, Option<String>>,
    pub updated_at: __sdk::__query_builder::Col<Entity, __sdk::Timestamp>,
    pub appearance: __sdk::__query_builder::Col<Entity, Option<String>>,
    pub equipment: __sdk::__query_builder::Col<Entity, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Entity {
    type Cols = EntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            type_id: __sdk::__query_builder::Col::new(table_name, "type_id"),
            type_name: __sdk::__query_builder::Col::new(table_name, "type_name"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            pitch: __sdk::__query_builder::Col::new(table_name, "pitch"),
            head_yaw: __sdk::__query_builder::Col::new(table_name, "head_yaw"),
            vx: __sdk::__query_builder::Col::new(table_name, "vx"),
            vy: __sdk::__query_builder::Col::new(table_name, "vy"),
            vz: __sdk::__query_builder::Col::new(table_name, "vz"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
            custom_name: __sdk::__query_builder::Col::new(table_name, "custom_name"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            appearance: __sdk::__query_builder::Col::new(table_name, "appearance"),
            equipment: __sdk::__query_builder::Col::new(table_name, "equipment"),
        }
    }
}

/// Indexed column accessor struct for the table `Entity`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityIxCols {
    pub id: __sdk::__query_builder::IxCol<Entity, i32>,
    pub type_name: __sdk::__query_builder::IxCol<Entity, String>,
}

impl __sdk::__query_builder::HasIxCols for Entity {
    type IxCols = EntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            type_name: __sdk::__query_builder::IxCol::new(table_name, "type_name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Entity {}
