// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod block_change_data_type;
pub mod block_change_table;
pub mod block_change_type;
pub mod block_entity_data_type;
pub mod block_entity_table;
pub mod block_entity_type;
pub mod block_state_def_type;
pub mod block_state_row_type;
pub mod block_state_table;
pub mod bot_command_table;
pub mod bot_command_type;
pub mod bot_status_table;
pub mod bot_status_type;
pub mod chunk_light_table;
pub mod chunk_light_type;
pub mod chunk_section_table;
pub mod chunk_section_type;
pub mod chunk_table;
pub mod chunk_type;
pub mod clear_world_reducer;
pub mod close_all_containers_reducer;
pub mod close_container_reducer;
pub mod complete_bot_command_reducer;
pub mod container_data_type;
pub mod container_table;
pub mod container_type;
pub mod entity_data_type;
pub mod entity_move_type;
pub mod entity_table;
pub mod entity_type;
pub mod expire_pending_bot_commands_reducer;
pub mod light_data_type;
pub mod monitor_data_type;
pub mod monitor_table;
pub mod monitor_type;
pub mod move_entities_reducer;
pub mod player_data_type;
pub mod player_table;
pub mod player_type;
pub mod registry_def_type;
pub mod registry_entry_table;
pub mod registry_entry_type;
pub mod remove_block_entities_reducer;
pub mod remove_entities_reducer;
pub mod remove_monitors_reducer;
pub mod remove_players_reducer;
pub mod request_click_slot_reducer;
pub mod request_close_container_reducer;
pub mod request_drag_reducer;
pub mod request_open_container_reducer;
pub mod request_walk_to_reducer;
pub mod section_data_type;
pub mod set_block_states_reducer;
pub mod set_bot_status_reducer;
pub mod set_container_slot_reducer;
pub mod set_entity_appearance_reducer;
pub mod set_entity_equipment_reducer;
pub mod set_entity_name_reducer;
pub mod set_registry_entries_reducer;
pub mod set_time_reducer;
pub mod unload_chunk_reducer;
pub mod update_light_reducer;
pub mod update_monitors_reducer;
pub mod update_sections_reducer;
pub mod upsert_block_entities_reducer;
pub mod upsert_chunk_reducer;
pub mod upsert_container_reducer;
pub mod upsert_entities_reducer;
pub mod upsert_players_reducer;
pub mod world_time_table;
pub mod world_time_type;

pub use block_change_data_type::BlockChangeData;
pub use block_change_table::*;
pub use block_change_type::BlockChange;
pub use block_entity_data_type::BlockEntityData;
pub use block_entity_table::*;
pub use block_entity_type::BlockEntity;
pub use block_state_def_type::BlockStateDef;
pub use block_state_row_type::BlockStateRow;
pub use block_state_table::*;
pub use bot_command_table::*;
pub use bot_command_type::BotCommand;
pub use bot_status_table::*;
pub use bot_status_type::BotStatus;
pub use chunk_light_table::*;
pub use chunk_light_type::ChunkLight;
pub use chunk_section_table::*;
pub use chunk_section_type::ChunkSection;
pub use chunk_table::*;
pub use chunk_type::Chunk;
pub use clear_world_reducer::clear_world;
pub use close_all_containers_reducer::close_all_containers;
pub use close_container_reducer::close_container;
pub use complete_bot_command_reducer::complete_bot_command;
pub use container_data_type::ContainerData;
pub use container_table::*;
pub use container_type::Container;
pub use entity_data_type::EntityData;
pub use entity_move_type::EntityMove;
pub use entity_table::*;
pub use entity_type::Entity;
pub use expire_pending_bot_commands_reducer::expire_pending_bot_commands;
pub use light_data_type::LightData;
pub use monitor_data_type::MonitorData;
pub use monitor_table::*;
pub use monitor_type::Monitor;
pub use move_entities_reducer::move_entities;
pub use player_data_type::PlayerData;
pub use player_table::*;
pub use player_type::Player;
pub use registry_def_type::RegistryDef;
pub use registry_entry_table::*;
pub use registry_entry_type::RegistryEntry;
pub use remove_block_entities_reducer::remove_block_entities;
pub use remove_entities_reducer::remove_entities;
pub use remove_monitors_reducer::remove_monitors;
pub use remove_players_reducer::remove_players;
pub use request_click_slot_reducer::request_click_slot;
pub use request_close_container_reducer::request_close_container;
pub use request_drag_reducer::request_drag;
pub use request_open_container_reducer::request_open_container;
pub use request_walk_to_reducer::request_walk_to;
pub use section_data_type::SectionData;
pub use set_block_states_reducer::set_block_states;
pub use set_bot_status_reducer::set_bot_status;
pub use set_container_slot_reducer::set_container_slot;
pub use set_entity_appearance_reducer::set_entity_appearance;
pub use set_entity_equipment_reducer::set_entity_equipment;
pub use set_entity_name_reducer::set_entity_name;
pub use set_registry_entries_reducer::set_registry_entries;
pub use set_time_reducer::set_time;
pub use unload_chunk_reducer::unload_chunk;
pub use update_light_reducer::update_light;
pub use update_monitors_reducer::update_monitors;
pub use update_sections_reducer::update_sections;
pub use upsert_block_entities_reducer::upsert_block_entities;
pub use upsert_chunk_reducer::upsert_chunk;
pub use upsert_container_reducer::upsert_container;
pub use upsert_entities_reducer::upsert_entities;
pub use upsert_players_reducer::upsert_players;
pub use world_time_table::*;
pub use world_time_type::WorldTime;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ClearWorld,
    CloseAllContainers,
    CloseContainer {
        window_id: i32,
    },
    CompleteBotCommand {
        id: u64,
        status: String,
        detail: String,
    },
    ExpirePendingBotCommands,
    MoveEntities {
        moves: Vec<EntityMove>,
    },
    RemoveBlockEntities {
        keys: Vec<i64>,
    },
    RemoveEntities {
        ids: Vec<i32>,
    },
    RemoveMonitors {
        keys: Vec<i64>,
    },
    RemovePlayers {
        uuids: Vec<String>,
    },
    RequestClickSlot {
        window_id: i32,
        slot: i32,
        button: i32,
        mode: i32,
    },
    RequestCloseContainer,
    RequestDrag {
        window_id: i32,
        slots: Vec<i32>,
        right: bool,
    },
    RequestOpenContainer {
        x: i32,
        y: i32,
        z: i32,
        face: String,
    },
    RequestWalkTo {
        x: i32,
        y: i32,
        z: i32,
    },
    SetBlockStates {
        defs: Vec<BlockStateDef>,
    },
    SetBotStatus {
        server_addr: String,
        username: String,
        state: String,
        detail: String,
        dimension: String,
        x: f64,
        y: f64,
        z: f64,
        view_distance: i32,
        chunks_loaded: u32,
        packets_seen: u64,
    },
    SetContainerSlot {
        window_id: i32,
        slot: i32,
        stack: String,
        state_id: i32,
    },
    SetEntityAppearance {
        id: i32,
        appearance: String,
    },
    SetEntityEquipment {
        id: i32,
        equipment: String,
    },
    SetEntityName {
        id: i32,
        custom_name: Option<String>,
    },
    SetRegistryEntries {
        defs: Vec<RegistryDef>,
    },
    SetTime {
        dimension: String,
        game_time: i64,
        day_time: i64,
    },
    UnloadChunk {
        cx: i32,
        cz: i32,
    },
    UpdateLight {
        cx: i32,
        cz: i32,
        sections: Vec<LightData>,
    },
    UpdateMonitors {
        items: Vec<MonitorData>,
    },
    UpdateSections {
        cx: i32,
        cz: i32,
        sections: Vec<SectionData>,
        changes: Vec<BlockChangeData>,
    },
    UpsertBlockEntities {
        items: Vec<BlockEntityData>,
    },
    UpsertChunk {
        dimension: String,
        cx: i32,
        cz: i32,
        min_section: i32,
        sections: Vec<SectionData>,
        block_entities: Vec<BlockEntityData>,
    },
    UpsertContainer {
        c: ContainerData,
    },
    UpsertEntities {
        items: Vec<EntityData>,
    },
    UpsertPlayers {
        items: Vec<PlayerData>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ClearWorld => "clear_world",
            Reducer::CloseAllContainers => "close_all_containers",
            Reducer::CloseContainer { .. } => "close_container",
            Reducer::CompleteBotCommand { .. } => "complete_bot_command",
            Reducer::ExpirePendingBotCommands => "expire_pending_bot_commands",
            Reducer::MoveEntities { .. } => "move_entities",
            Reducer::RemoveBlockEntities { .. } => "remove_block_entities",
            Reducer::RemoveEntities { .. } => "remove_entities",
            Reducer::RemoveMonitors { .. } => "remove_monitors",
            Reducer::RemovePlayers { .. } => "remove_players",
            Reducer::RequestClickSlot { .. } => "request_click_slot",
            Reducer::RequestCloseContainer => "request_close_container",
            Reducer::RequestDrag { .. } => "request_drag",
            Reducer::RequestOpenContainer { .. } => "request_open_container",
            Reducer::RequestWalkTo { .. } => "request_walk_to",
            Reducer::SetBlockStates { .. } => "set_block_states",
            Reducer::SetBotStatus { .. } => "set_bot_status",
            Reducer::SetContainerSlot { .. } => "set_container_slot",
            Reducer::SetEntityAppearance { .. } => "set_entity_appearance",
            Reducer::SetEntityEquipment { .. } => "set_entity_equipment",
            Reducer::SetEntityName { .. } => "set_entity_name",
            Reducer::SetRegistryEntries { .. } => "set_registry_entries",
            Reducer::SetTime { .. } => "set_time",
            Reducer::UnloadChunk { .. } => "unload_chunk",
            Reducer::UpdateLight { .. } => "update_light",
            Reducer::UpdateMonitors { .. } => "update_monitors",
            Reducer::UpdateSections { .. } => "update_sections",
            Reducer::UpsertBlockEntities { .. } => "upsert_block_entities",
            Reducer::UpsertChunk { .. } => "upsert_chunk",
            Reducer::UpsertContainer { .. } => "upsert_container",
            Reducer::UpsertEntities { .. } => "upsert_entities",
            Reducer::UpsertPlayers { .. } => "upsert_players",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::ClearWorld => __sats::bsatn::to_vec(&clear_world_reducer::ClearWorldArgs {}),
            Reducer::CloseAllContainers => {
                __sats::bsatn::to_vec(&close_all_containers_reducer::CloseAllContainersArgs {})
            }
            Reducer::CloseContainer { window_id } => {
                __sats::bsatn::to_vec(&close_container_reducer::CloseContainerArgs {
                    window_id: window_id.clone(),
                })
            }
            Reducer::CompleteBotCommand { id, status, detail } => {
                __sats::bsatn::to_vec(&complete_bot_command_reducer::CompleteBotCommandArgs {
                    id: id.clone(),
                    status: status.clone(),
                    detail: detail.clone(),
                })
            }
            Reducer::ExpirePendingBotCommands => __sats::bsatn::to_vec(
                &expire_pending_bot_commands_reducer::ExpirePendingBotCommandsArgs {},
            ),
            Reducer::MoveEntities { moves } => {
                __sats::bsatn::to_vec(&move_entities_reducer::MoveEntitiesArgs {
                    moves: moves.clone(),
                })
            }
            Reducer::RemoveBlockEntities { keys } => {
                __sats::bsatn::to_vec(&remove_block_entities_reducer::RemoveBlockEntitiesArgs {
                    keys: keys.clone(),
                })
            }
            Reducer::RemoveEntities { ids } => {
                __sats::bsatn::to_vec(&remove_entities_reducer::RemoveEntitiesArgs {
                    ids: ids.clone(),
                })
            }
            Reducer::RemoveMonitors { keys } => {
                __sats::bsatn::to_vec(&remove_monitors_reducer::RemoveMonitorsArgs {
                    keys: keys.clone(),
                })
            }
            Reducer::RemovePlayers { uuids } => {
                __sats::bsatn::to_vec(&remove_players_reducer::RemovePlayersArgs {
                    uuids: uuids.clone(),
                })
            }
            Reducer::RequestClickSlot {
                window_id,
                slot,
                button,
                mode,
            } => __sats::bsatn::to_vec(&request_click_slot_reducer::RequestClickSlotArgs {
                window_id: window_id.clone(),
                slot: slot.clone(),
                button: button.clone(),
                mode: mode.clone(),
            }),
            Reducer::RequestCloseContainer => __sats::bsatn::to_vec(
                &request_close_container_reducer::RequestCloseContainerArgs {},
            ),
            Reducer::RequestDrag {
                window_id,
                slots,
                right,
            } => __sats::bsatn::to_vec(&request_drag_reducer::RequestDragArgs {
                window_id: window_id.clone(),
                slots: slots.clone(),
                right: right.clone(),
            }),
            Reducer::RequestOpenContainer { x, y, z, face } => {
                __sats::bsatn::to_vec(&request_open_container_reducer::RequestOpenContainerArgs {
                    x: x.clone(),
                    y: y.clone(),
                    z: z.clone(),
                    face: face.clone(),
                })
            }
            Reducer::RequestWalkTo { x, y, z } => {
                __sats::bsatn::to_vec(&request_walk_to_reducer::RequestWalkToArgs {
                    x: x.clone(),
                    y: y.clone(),
                    z: z.clone(),
                })
            }
            Reducer::SetBlockStates { defs } => {
                __sats::bsatn::to_vec(&set_block_states_reducer::SetBlockStatesArgs {
                    defs: defs.clone(),
                })
            }
            Reducer::SetBotStatus {
                server_addr,
                username,
                state,
                detail,
                dimension,
                x,
                y,
                z,
                view_distance,
                chunks_loaded,
                packets_seen,
            } => __sats::bsatn::to_vec(&set_bot_status_reducer::SetBotStatusArgs {
                server_addr: server_addr.clone(),
                username: username.clone(),
                state: state.clone(),
                detail: detail.clone(),
                dimension: dimension.clone(),
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
                view_distance: view_distance.clone(),
                chunks_loaded: chunks_loaded.clone(),
                packets_seen: packets_seen.clone(),
            }),
            Reducer::SetContainerSlot {
                window_id,
                slot,
                stack,
                state_id,
            } => __sats::bsatn::to_vec(&set_container_slot_reducer::SetContainerSlotArgs {
                window_id: window_id.clone(),
                slot: slot.clone(),
                stack: stack.clone(),
                state_id: state_id.clone(),
            }),
            Reducer::SetEntityAppearance { id, appearance } => {
                __sats::bsatn::to_vec(&set_entity_appearance_reducer::SetEntityAppearanceArgs {
                    id: id.clone(),
                    appearance: appearance.clone(),
                })
            }
            Reducer::SetEntityEquipment { id, equipment } => {
                __sats::bsatn::to_vec(&set_entity_equipment_reducer::SetEntityEquipmentArgs {
                    id: id.clone(),
                    equipment: equipment.clone(),
                })
            }
            Reducer::SetEntityName { id, custom_name } => {
                __sats::bsatn::to_vec(&set_entity_name_reducer::SetEntityNameArgs {
                    id: id.clone(),
                    custom_name: custom_name.clone(),
                })
            }
            Reducer::SetRegistryEntries { defs } => {
                __sats::bsatn::to_vec(&set_registry_entries_reducer::SetRegistryEntriesArgs {
                    defs: defs.clone(),
                })
            }
            Reducer::SetTime {
                dimension,
                game_time,
                day_time,
            } => __sats::bsatn::to_vec(&set_time_reducer::SetTimeArgs {
                dimension: dimension.clone(),
                game_time: game_time.clone(),
                day_time: day_time.clone(),
            }),
            Reducer::UnloadChunk { cx, cz } => {
                __sats::bsatn::to_vec(&unload_chunk_reducer::UnloadChunkArgs {
                    cx: cx.clone(),
                    cz: cz.clone(),
                })
            }
            Reducer::UpdateLight { cx, cz, sections } => {
                __sats::bsatn::to_vec(&update_light_reducer::UpdateLightArgs {
                    cx: cx.clone(),
                    cz: cz.clone(),
                    sections: sections.clone(),
                })
            }
            Reducer::UpdateMonitors { items } => {
                __sats::bsatn::to_vec(&update_monitors_reducer::UpdateMonitorsArgs {
                    items: items.clone(),
                })
            }
            Reducer::UpdateSections {
                cx,
                cz,
                sections,
                changes,
            } => __sats::bsatn::to_vec(&update_sections_reducer::UpdateSectionsArgs {
                cx: cx.clone(),
                cz: cz.clone(),
                sections: sections.clone(),
                changes: changes.clone(),
            }),
            Reducer::UpsertBlockEntities { items } => {
                __sats::bsatn::to_vec(&upsert_block_entities_reducer::UpsertBlockEntitiesArgs {
                    items: items.clone(),
                })
            }
            Reducer::UpsertChunk {
                dimension,
                cx,
                cz,
                min_section,
                sections,
                block_entities,
            } => __sats::bsatn::to_vec(&upsert_chunk_reducer::UpsertChunkArgs {
                dimension: dimension.clone(),
                cx: cx.clone(),
                cz: cz.clone(),
                min_section: min_section.clone(),
                sections: sections.clone(),
                block_entities: block_entities.clone(),
            }),
            Reducer::UpsertContainer { c } => {
                __sats::bsatn::to_vec(&upsert_container_reducer::UpsertContainerArgs {
                    c: c.clone(),
                })
            }
            Reducer::UpsertEntities { items } => {
                __sats::bsatn::to_vec(&upsert_entities_reducer::UpsertEntitiesArgs {
                    items: items.clone(),
                })
            }
            Reducer::UpsertPlayers { items } => {
                __sats::bsatn::to_vec(&upsert_players_reducer::UpsertPlayersArgs {
                    items: items.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    block_change: __sdk::TableUpdate<BlockChange>,
    block_entity: __sdk::TableUpdate<BlockEntity>,
    block_state: __sdk::TableUpdate<BlockStateRow>,
    bot_command: __sdk::TableUpdate<BotCommand>,
    bot_status: __sdk::TableUpdate<BotStatus>,
    chunk: __sdk::TableUpdate<Chunk>,
    chunk_light: __sdk::TableUpdate<ChunkLight>,
    chunk_section: __sdk::TableUpdate<ChunkSection>,
    container: __sdk::TableUpdate<Container>,
    entity: __sdk::TableUpdate<Entity>,
    monitor: __sdk::TableUpdate<Monitor>,
    player: __sdk::TableUpdate<Player>,
    registry_entry: __sdk::TableUpdate<RegistryEntry>,
    world_time: __sdk::TableUpdate<WorldTime>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "block_change" => db_update
                    .block_change
                    .append(block_change_table::parse_table_update(table_update)?),
                "block_entity" => db_update
                    .block_entity
                    .append(block_entity_table::parse_table_update(table_update)?),
                "block_state" => db_update
                    .block_state
                    .append(block_state_table::parse_table_update(table_update)?),
                "bot_command" => db_update
                    .bot_command
                    .append(bot_command_table::parse_table_update(table_update)?),
                "bot_status" => db_update
                    .bot_status
                    .append(bot_status_table::parse_table_update(table_update)?),
                "chunk" => db_update
                    .chunk
                    .append(chunk_table::parse_table_update(table_update)?),
                "chunk_light" => db_update
                    .chunk_light
                    .append(chunk_light_table::parse_table_update(table_update)?),
                "chunk_section" => db_update
                    .chunk_section
                    .append(chunk_section_table::parse_table_update(table_update)?),
                "container" => db_update
                    .container
                    .append(container_table::parse_table_update(table_update)?),
                "entity" => db_update
                    .entity
                    .append(entity_table::parse_table_update(table_update)?),
                "monitor" => db_update
                    .monitor
                    .append(monitor_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "registry_entry" => db_update
                    .registry_entry
                    .append(registry_entry_table::parse_table_update(table_update)?),
                "world_time" => db_update
                    .world_time
                    .append(world_time_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.block_change = cache
            .apply_diff_to_table::<BlockChange>("block_change", &self.block_change)
            .with_updates_by_pk(|row| &row.seq);
        diff.block_entity = cache
            .apply_diff_to_table::<BlockEntity>("block_entity", &self.block_entity)
            .with_updates_by_pk(|row| &row.key);
        diff.block_state = cache
            .apply_diff_to_table::<BlockStateRow>("block_state", &self.block_state)
            .with_updates_by_pk(|row| &row.id);
        diff.bot_command = cache
            .apply_diff_to_table::<BotCommand>("bot_command", &self.bot_command)
            .with_updates_by_pk(|row| &row.id);
        diff.bot_status = cache
            .apply_diff_to_table::<BotStatus>("bot_status", &self.bot_status)
            .with_updates_by_pk(|row| &row.id);
        diff.chunk = cache
            .apply_diff_to_table::<Chunk>("chunk", &self.chunk)
            .with_updates_by_pk(|row| &row.key);
        diff.chunk_light = cache
            .apply_diff_to_table::<ChunkLight>("chunk_light", &self.chunk_light)
            .with_updates_by_pk(|row| &row.key);
        diff.chunk_section = cache
            .apply_diff_to_table::<ChunkSection>("chunk_section", &self.chunk_section)
            .with_updates_by_pk(|row| &row.key);
        diff.container = cache
            .apply_diff_to_table::<Container>("container", &self.container)
            .with_updates_by_pk(|row| &row.window_id);
        diff.entity = cache
            .apply_diff_to_table::<Entity>("entity", &self.entity)
            .with_updates_by_pk(|row| &row.id);
        diff.monitor = cache
            .apply_diff_to_table::<Monitor>("monitor", &self.monitor)
            .with_updates_by_pk(|row| &row.key);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.uuid);
        diff.registry_entry = cache
            .apply_diff_to_table::<RegistryEntry>("registry_entry", &self.registry_entry)
            .with_updates_by_pk(|row| &row.key);
        diff.world_time = cache
            .apply_diff_to_table::<WorldTime>("world_time", &self.world_time)
            .with_updates_by_pk(|row| &row.dimension);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "block_change" => db_update
                    .block_change
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "block_entity" => db_update
                    .block_entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "block_state" => db_update
                    .block_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "bot_command" => db_update
                    .bot_command
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "bot_status" => db_update
                    .bot_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "chunk" => db_update
                    .chunk
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "chunk_light" => db_update
                    .chunk_light
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "chunk_section" => db_update
                    .chunk_section
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "container" => db_update
                    .container
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "monitor" => db_update
                    .monitor
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "registry_entry" => db_update
                    .registry_entry
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_time" => db_update
                    .world_time
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "block_change" => db_update
                    .block_change
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "block_entity" => db_update
                    .block_entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "block_state" => db_update
                    .block_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "bot_command" => db_update
                    .bot_command
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "bot_status" => db_update
                    .bot_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "chunk" => db_update
                    .chunk
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "chunk_light" => db_update
                    .chunk_light
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "chunk_section" => db_update
                    .chunk_section
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "container" => db_update
                    .container
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "monitor" => db_update
                    .monitor
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "registry_entry" => db_update
                    .registry_entry
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_time" => db_update
                    .world_time
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    block_change: __sdk::TableAppliedDiff<'r, BlockChange>,
    block_entity: __sdk::TableAppliedDiff<'r, BlockEntity>,
    block_state: __sdk::TableAppliedDiff<'r, BlockStateRow>,
    bot_command: __sdk::TableAppliedDiff<'r, BotCommand>,
    bot_status: __sdk::TableAppliedDiff<'r, BotStatus>,
    chunk: __sdk::TableAppliedDiff<'r, Chunk>,
    chunk_light: __sdk::TableAppliedDiff<'r, ChunkLight>,
    chunk_section: __sdk::TableAppliedDiff<'r, ChunkSection>,
    container: __sdk::TableAppliedDiff<'r, Container>,
    entity: __sdk::TableAppliedDiff<'r, Entity>,
    monitor: __sdk::TableAppliedDiff<'r, Monitor>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    registry_entry: __sdk::TableAppliedDiff<'r, RegistryEntry>,
    world_time: __sdk::TableAppliedDiff<'r, WorldTime>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<BlockChange>(
            "block_change",
            &self.block_change,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BlockEntity>(
            "block_entity",
            &self.block_entity,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BlockStateRow>(
            "block_state",
            &self.block_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BotCommand>("bot_command", &self.bot_command, event);
        callbacks.invoke_table_row_callbacks::<BotStatus>("bot_status", &self.bot_status, event);
        callbacks.invoke_table_row_callbacks::<Chunk>("chunk", &self.chunk, event);
        callbacks.invoke_table_row_callbacks::<ChunkLight>("chunk_light", &self.chunk_light, event);
        callbacks.invoke_table_row_callbacks::<ChunkSection>(
            "chunk_section",
            &self.chunk_section,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Container>("container", &self.container, event);
        callbacks.invoke_table_row_callbacks::<Entity>("entity", &self.entity, event);
        callbacks.invoke_table_row_callbacks::<Monitor>("monitor", &self.monitor, event);
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<RegistryEntry>(
            "registry_entry",
            &self.registry_entry,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WorldTime>("world_time", &self.world_time, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        block_change_table::register_table(client_cache);
        block_entity_table::register_table(client_cache);
        block_state_table::register_table(client_cache);
        bot_command_table::register_table(client_cache);
        bot_status_table::register_table(client_cache);
        chunk_table::register_table(client_cache);
        chunk_light_table::register_table(client_cache);
        chunk_section_table::register_table(client_cache);
        container_table::register_table(client_cache);
        entity_table::register_table(client_cache);
        monitor_table::register_table(client_cache);
        player_table::register_table(client_cache);
        registry_entry_table::register_table(client_cache);
        world_time_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "block_change",
        "block_entity",
        "block_state",
        "bot_command",
        "bot_status",
        "chunk",
        "chunk_light",
        "chunk_section",
        "container",
        "entity",
        "monitor",
        "player",
        "registry_entry",
        "world_time",
    ];
}
