// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::monitor_type::Monitor;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `monitor`.
///
/// Obtain a handle from the [`MonitorTableAccess::monitor`] method on [`super::RemoteTables`],
/// like `ctx.db.monitor()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.monitor().on_insert(...)`.
pub struct MonitorTableHandle<'ctx> {
    imp: __sdk::TableHandle<Monitor>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `monitor`.
pub struct MonitorTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MonitorTableAccessor {
    type Row = Monitor;
    type Handle<'db> = MonitorTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.monitor()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `monitor`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MonitorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MonitorTableHandle`], which mediates access to the table `monitor`.
    fn monitor(&self) -> MonitorTableHandle<'_>;
}

impl MonitorTableAccess for super::RemoteTables {
    fn monitor(&self) -> MonitorTableHandle<'_> {
        MonitorTableHandle {
            imp: self.imp.get_table::<Monitor>("monitor"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MonitorInsertCallbackId(__sdk::CallbackId);
pub struct MonitorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MonitorTableHandle<'ctx> {
    type Row = Monitor;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Monitor> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MonitorTableHandle<'ctx> {
    type Row = Monitor;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Monitor> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MonitorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MonitorInsertCallbackId {
        MonitorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MonitorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MonitorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MonitorDeleteCallbackId {
        MonitorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MonitorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MonitorTableHandle<'ctx> {
    type InsertCallbackId = MonitorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MonitorInsertCallbackId {
        MonitorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MonitorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MonitorTableHandle<'ctx> {
    type DeleteCallbackId = MonitorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MonitorDeleteCallbackId {
        MonitorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MonitorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MonitorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MonitorTableHandle<'ctx> {
    type UpdateCallbackId = MonitorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MonitorUpdateCallbackId {
        MonitorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MonitorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MonitorTableHandle<'ctx> {
    type UpdateCallbackId = MonitorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MonitorUpdateCallbackId {
        MonitorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MonitorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `monitor`,
/// which allows point queries on the field of the same name
/// via the [`MonitorKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.monitor().key().find(...)`.
pub struct MonitorKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Monitor, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MonitorTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `monitor`.
    pub fn key(&self) -> MonitorKeyUnique<'ctx> {
        MonitorKeyUnique {
            imp: self.imp.get_unique_constraint::<i64>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MonitorKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<Monitor> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Monitor>("monitor");
    _table.add_unique_constraint::<i64>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Monitor>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Monitor>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Monitor`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait monitorQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Monitor`.
    fn monitor(&self) -> __sdk::__query_builder::Table<Monitor>;
}

impl monitorQueryTableAccess for __sdk::QueryTableAccessor {
    fn monitor(&self) -> __sdk::__query_builder::Table<Monitor> {
        __sdk::__query_builder::Table::new("monitor")
    }
}
