// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Monitor {
    pub key: i64,
    pub chunk_key: i64,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub facing: String,
    pub block_width: u32,
    pub block_height: u32,
    pub term_width: u32,
    pub term_height: u32,
    pub colour: bool,
    pub cursor_x: i32,
    pub cursor_y: i32,
    pub cursor_blink: bool,
    pub cursor_fg: u8,
    pub cursor_bg: u8,
    pub has_screen: bool,
    pub lines: Vec<String>,
    pub fg: Vec<String>,
    pub bg: Vec<String>,
    pub palette: Vec<String>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Monitor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Monitor`.
///
/// Provides typed access to columns for query building.
pub struct MonitorCols {
    pub key: __sdk::__query_builder::Col<Monitor, i64>,
    pub chunk_key: __sdk::__query_builder::Col<Monitor, i64>,
    pub x: __sdk::__query_builder::Col<Monitor, i32>,
    pub y: __sdk::__query_builder::Col<Monitor, i32>,
    pub z: __sdk::__query_builder::Col<Monitor, i32>,
    pub facing: __sdk::__query_builder::Col<Monitor, String>,
    pub block_width: __sdk::__query_builder::Col<Monitor, u32>,
    pub block_height: __sdk::__query_builder::Col<Monitor, u32>,
    pub term_width: __sdk::__query_builder::Col<Monitor, u32>,
    pub term_height: __sdk::__query_builder::Col<Monitor, u32>,
    pub colour: __sdk::__query_builder::Col<Monitor, bool>,
    pub cursor_x: __sdk::__query_builder::Col<Monitor, i32>,
    pub cursor_y: __sdk::__query_builder::Col<Monitor, i32>,
    pub cursor_blink: __sdk::__query_builder::Col<Monitor, bool>,
    pub cursor_fg: __sdk::__query_builder::Col<Monitor, u8>,
    pub cursor_bg: __sdk::__query_builder::Col<Monitor, u8>,
    pub has_screen: __sdk::__query_builder::Col<Monitor, bool>,
    pub lines: __sdk::__query_builder::Col<Monitor, Vec<String>>,
    pub fg: __sdk::__query_builder::Col<Monitor, Vec<String>>,
    pub bg: __sdk::__query_builder::Col<Monitor, Vec<String>>,
    pub palette: __sdk::__query_builder::Col<Monitor, Vec<String>>,
    pub updated_at: __sdk::__query_builder::Col<Monitor, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Monitor {
    type Cols = MonitorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MonitorCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            facing: __sdk::__query_builder::Col::new(table_name, "facing"),
            block_width: __sdk::__query_builder::Col::new(table_name, "block_width"),
            block_height: __sdk::__query_builder::Col::new(table_name, "block_height"),
            term_width: __sdk::__query_builder::Col::new(table_name, "term_width"),
            term_height: __sdk::__query_builder::Col::new(table_name, "term_height"),
            colour: __sdk::__query_builder::Col::new(table_name, "colour"),
            cursor_x: __sdk::__query_builder::Col::new(table_name, "cursor_x"),
            cursor_y: __sdk::__query_builder::Col::new(table_name, "cursor_y"),
            cursor_blink: __sdk::__query_builder::Col::new(table_name, "cursor_blink"),
            cursor_fg: __sdk::__query_builder::Col::new(table_name, "cursor_fg"),
            cursor_bg: __sdk::__query_builder::Col::new(table_name, "cursor_bg"),
            has_screen: __sdk::__query_builder::Col::new(table_name, "has_screen"),
            lines: __sdk::__query_builder::Col::new(table_name, "lines"),
            fg: __sdk::__query_builder::Col::new(table_name, "fg"),
            bg: __sdk::__query_builder::Col::new(table_name, "bg"),
            palette: __sdk::__query_builder::Col::new(table_name, "palette"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Monitor`.
///
/// Provides typed access to indexed columns for query building.
pub struct MonitorIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<Monitor, i64>,
    pub key: __sdk::__query_builder::IxCol<Monitor, i64>,
}

impl __sdk::__query_builder::HasIxCols for Monitor {
    type IxCols = MonitorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MonitorIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Monitor {}
