// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MonitorData {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub facing: String,
    pub block_width: u32,
    pub block_height: u32,
    pub term_width: u32,
    pub term_height: u32,
    pub colour: bool,
    pub cursor_x: i32,
    pub cursor_y: i32,
    pub cursor_blink: bool,
    pub cursor_fg: u8,
    pub cursor_bg: u8,
    pub has_screen: bool,
    pub lines: Vec<String>,
    pub fg: Vec<String>,
    pub bg: Vec<String>,
    pub palette: Vec<String>,
}

impl __sdk::InModule for MonitorData {
    type Module = super::RemoteModule;
}
