// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::entity_move_type::EntityMove;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveEntitiesArgs {
    pub moves: Vec<EntityMove>,
}

impl From<MoveEntitiesArgs> for super::Reducer {
    fn from(args: MoveEntitiesArgs) -> Self {
        Self::MoveEntities { moves: args.moves }
    }
}

impl __sdk::InModule for MoveEntitiesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_entities`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_entities {
    /// Request that the remote module invoke the reducer `move_entities` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_entities:move_entities_then`] to run a callback after the reducer completes.
    fn move_entities(&self, moves: Vec<EntityMove>) -> __sdk::Result<()> {
        self.move_entities_then(moves, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_entities` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_entities_then(
        &self,
        moves: Vec<EntityMove>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_entities for super::RemoteReducers {
    fn move_entities_then(
        &self,
        moves: Vec<EntityMove>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MoveEntitiesArgs { moves }, callback)
    }
}
