// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub uuid: String,
    pub name: String,
    pub entity_id: Option<i32>,
    pub online: bool,
    pub gamemode: i32,
    pub latency: i32,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub pitch: f32,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub uuid: __sdk::__query_builder::Col<Player, String>,
    pub name: __sdk::__query_builder::Col<Player, String>,
    pub entity_id: __sdk::__query_builder::Col<Player, Option<i32>>,
    pub online: __sdk::__query_builder::Col<Player, bool>,
    pub gamemode: __sdk::__query_builder::Col<Player, i32>,
    pub latency: __sdk::__query_builder::Col<Player, i32>,
    pub x: __sdk::__query_builder::Col<Player, f64>,
    pub y: __sdk::__query_builder::Col<Player, f64>,
    pub z: __sdk::__query_builder::Col<Player, f64>,
    pub yaw: __sdk::__query_builder::Col<Player, f32>,
    pub pitch: __sdk::__query_builder::Col<Player, f32>,
    pub updated_at: __sdk::__query_builder::Col<Player, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            online: __sdk::__query_builder::Col::new(table_name, "online"),
            gamemode: __sdk::__query_builder::Col::new(table_name, "gamemode"),
            latency: __sdk::__query_builder::Col::new(table_name, "latency"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            pitch: __sdk::__query_builder::Col::new(table_name, "pitch"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub name: __sdk::__query_builder::IxCol<Player, String>,
    pub uuid: __sdk::__query_builder::IxCol<Player, String>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            uuid: __sdk::__query_builder::IxCol::new(table_name, "uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
