// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RegistryEntry {
    pub key: String,
    pub registry: String,
    pub id: u32,
    pub name: String,
}

impl __sdk::InModule for RegistryEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RegistryEntry`.
///
/// Provides typed access to columns for query building.
pub struct RegistryEntryCols {
    pub key: __sdk::__query_builder::Col<RegistryEntry, String>,
    pub registry: __sdk::__query_builder::Col<RegistryEntry, String>,
    pub id: __sdk::__query_builder::Col<RegistryEntry, u32>,
    pub name: __sdk::__query_builder::Col<RegistryEntry, String>,
}

impl __sdk::__query_builder::HasCols for RegistryEntry {
    type Cols = RegistryEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RegistryEntryCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            registry: __sdk::__query_builder::Col::new(table_name, "registry"),
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `RegistryEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct RegistryEntryIxCols {
    pub key: __sdk::__query_builder::IxCol<RegistryEntry, String>,
}

impl __sdk::__query_builder::HasIxCols for RegistryEntry {
    type IxCols = RegistryEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RegistryEntryIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RegistryEntry {}
