// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::registry_entry_type::RegistryEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `registry_entry`.
///
/// Obtain a handle from the [`RegistryEntryTableAccess::registry_entry`] method on [`super::RemoteTables`],
/// like `ctx.db.registry_entry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.registry_entry().on_insert(...)`.
pub struct RegistryEntryTableHandle<'ctx> {
    imp: __sdk::TableHandle<RegistryEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `registry_entry`.
pub struct RegistryEntryTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RegistryEntryTableAccessor {
    type Row = RegistryEntry;
    type Handle<'db> = RegistryEntryTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.registry_entry()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `registry_entry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RegistryEntryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RegistryEntryTableHandle`], which mediates access to the table `registry_entry`.
    fn registry_entry(&self) -> RegistryEntryTableHandle<'_>;
}

impl RegistryEntryTableAccess for super::RemoteTables {
    fn registry_entry(&self) -> RegistryEntryTableHandle<'_> {
        RegistryEntryTableHandle {
            imp: self.imp.get_table::<RegistryEntry>("registry_entry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RegistryEntryInsertCallbackId(__sdk::CallbackId);
pub struct RegistryEntryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RegistryEntryTableHandle<'ctx> {
    type Row = RegistryEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RegistryEntry> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RegistryEntryTableHandle<'ctx> {
    type Row = RegistryEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RegistryEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RegistryEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegistryEntryInsertCallbackId {
        RegistryEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RegistryEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RegistryEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegistryEntryDeleteCallbackId {
        RegistryEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RegistryEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RegistryEntryTableHandle<'ctx> {
    type InsertCallbackId = RegistryEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegistryEntryInsertCallbackId {
        RegistryEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RegistryEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RegistryEntryTableHandle<'ctx> {
    type DeleteCallbackId = RegistryEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegistryEntryDeleteCallbackId {
        RegistryEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RegistryEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RegistryEntryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RegistryEntryTableHandle<'ctx> {
    type UpdateCallbackId = RegistryEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RegistryEntryUpdateCallbackId {
        RegistryEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RegistryEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RegistryEntryTableHandle<'ctx> {
    type UpdateCallbackId = RegistryEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RegistryEntryUpdateCallbackId {
        RegistryEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RegistryEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `registry_entry`,
/// which allows point queries on the field of the same name
/// via the [`RegistryEntryKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.registry_entry().key().find(...)`.
pub struct RegistryEntryKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RegistryEntry, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RegistryEntryTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `registry_entry`.
    pub fn key(&self) -> RegistryEntryKeyUnique<'ctx> {
        RegistryEntryKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RegistryEntryKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RegistryEntry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RegistryEntry>("registry_entry");
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RegistryEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RegistryEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RegistryEntry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait registry_entryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RegistryEntry`.
    fn registry_entry(&self) -> __sdk::__query_builder::Table<RegistryEntry>;
}

impl registry_entryQueryTableAccess for __sdk::QueryTableAccessor {
    fn registry_entry(&self) -> __sdk::__query_builder::Table<RegistryEntry> {
        __sdk::__query_builder::Table::new("registry_entry")
    }
}
