// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestClickSlotArgs {
    pub window_id: i32,
    pub slot: i32,
    pub button: i32,
    pub mode: i32,
}

impl From<RequestClickSlotArgs> for super::Reducer {
    fn from(args: RequestClickSlotArgs) -> Self {
        Self::RequestClickSlot {
            window_id: args.window_id,
            slot: args.slot,
            button: args.button,
            mode: args.mode,
        }
    }
}

impl __sdk::InModule for RequestClickSlotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_click_slot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_click_slot {
    /// Request that the remote module invoke the reducer `request_click_slot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_click_slot:request_click_slot_then`] to run a callback after the reducer completes.
    fn request_click_slot(
        &self,
        window_id: i32,
        slot: i32,
        button: i32,
        mode: i32,
    ) -> __sdk::Result<()> {
        self.request_click_slot_then(window_id, slot, button, mode, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_click_slot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_click_slot_then(
        &self,
        window_id: i32,
        slot: i32,
        button: i32,
        mode: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_click_slot for super::RemoteReducers {
    fn request_click_slot_then(
        &self,
        window_id: i32,
        slot: i32,
        button: i32,
        mode: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestClickSlotArgs {
                window_id,
                slot,
                button,
                mode,
            },
            callback,
        )
    }
}
