// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestDragArgs {
    pub window_id: i32,
    pub slots: Vec<i32>,
    pub right: bool,
}

impl From<RequestDragArgs> for super::Reducer {
    fn from(args: RequestDragArgs) -> Self {
        Self::RequestDrag {
            window_id: args.window_id,
            slots: args.slots,
            right: args.right,
        }
    }
}

impl __sdk::InModule for RequestDragArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_drag`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_drag {
    /// Request that the remote module invoke the reducer `request_drag` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_drag:request_drag_then`] to run a callback after the reducer completes.
    fn request_drag(&self, window_id: i32, slots: Vec<i32>, right: bool) -> __sdk::Result<()> {
        self.request_drag_then(window_id, slots, right, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_drag` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_drag_then(
        &self,
        window_id: i32,
        slots: Vec<i32>,
        right: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_drag for super::RemoteReducers {
    fn request_drag_then(
        &self,
        window_id: i32,
        slots: Vec<i32>,
        right: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestDragArgs {
                window_id,
                slots,
                right,
            },
            callback,
        )
    }
}
