// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestWalkToArgs {
    pub x: i32,
    pub y: i32,
    pub z: i32,
}

impl From<RequestWalkToArgs> for super::Reducer {
    fn from(args: RequestWalkToArgs) -> Self {
        Self::RequestWalkTo {
            x: args.x,
            y: args.y,
            z: args.z,
        }
    }
}

impl __sdk::InModule for RequestWalkToArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_walk_to`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_walk_to {
    /// Request that the remote module invoke the reducer `request_walk_to` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_walk_to:request_walk_to_then`] to run a callback after the reducer completes.
    fn request_walk_to(&self, x: i32, y: i32, z: i32) -> __sdk::Result<()> {
        self.request_walk_to_then(x, y, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_walk_to` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_walk_to_then(
        &self,
        x: i32,
        y: i32,
        z: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_walk_to for super::RemoteReducers {
    fn request_walk_to_then(
        &self,
        x: i32,
        y: i32,
        z: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RequestWalkToArgs { x, y, z }, callback)
    }
}
