// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestOpenContainerArgs {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub face: String,
}

impl From<RequestOpenContainerArgs> for super::Reducer {
    fn from(args: RequestOpenContainerArgs) -> Self {
        Self::RequestOpenContainer {
            x: args.x,
            y: args.y,
            z: args.z,
            face: args.face,
        }
    }
}

impl __sdk::InModule for RequestOpenContainerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_open_container`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_open_container {
    /// Request that the remote module invoke the reducer `request_open_container` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_open_container:request_open_container_then`] to run a callback after the reducer completes.
    fn request_open_container(&self, x: i32, y: i32, z: i32, face: String) -> __sdk::Result<()> {
        self.request_open_container_then(x, y, z, face, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_open_container` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_open_container_then(
        &self,
        x: i32,
        y: i32,
        z: i32,
        face: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_open_container for super::RemoteReducers {
    fn request_open_container_then(
        &self,
        x: i32,
        y: i32,
        z: i32,
        face: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RequestOpenContainerArgs { x, y, z, face }, callback)
    }
}
