// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SectionData {
    pub sy: i32,
    pub non_air_count: u16,
    pub block_bits: u8,
    pub block_palette: Vec<u32>,
    pub block_data: Vec<u64>,
    pub biome_bits: u8,
    pub biome_palette: Vec<u32>,
    pub biome_data: Vec<u64>,
    pub sky_light: Vec<u8>,
    pub block_light: Vec<u8>,
}

impl __sdk::InModule for SectionData {
    type Module = super::RemoteModule;
}
