// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetBotStatusArgs {
    pub server_addr: String,
    pub username: String,
    pub state: String,
    pub detail: String,
    pub dimension: String,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub view_distance: i32,
    pub chunks_loaded: u32,
    pub packets_seen: u64,
}

impl From<SetBotStatusArgs> for super::Reducer {
    fn from(args: SetBotStatusArgs) -> Self {
        Self::SetBotStatus {
            server_addr: args.server_addr,
            username: args.username,
            state: args.state,
            detail: args.detail,
            dimension: args.dimension,
            x: args.x,
            y: args.y,
            z: args.z,
            view_distance: args.view_distance,
            chunks_loaded: args.chunks_loaded,
            packets_seen: args.packets_seen,
        }
    }
}

impl __sdk::InModule for SetBotStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_bot_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_bot_status {
    /// Request that the remote module invoke the reducer `set_bot_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_bot_status:set_bot_status_then`] to run a callback after the reducer completes.
    fn set_bot_status(
        &self,
        server_addr: String,
        username: String,
        state: String,
        detail: String,
        dimension: String,
        x: f64,
        y: f64,
        z: f64,
        view_distance: i32,
        chunks_loaded: u32,
        packets_seen: u64,
    ) -> __sdk::Result<()> {
        self.set_bot_status_then(
            server_addr,
            username,
            state,
            detail,
            dimension,
            x,
            y,
            z,
            view_distance,
            chunks_loaded,
            packets_seen,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_bot_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_bot_status_then(
        &self,
        server_addr: String,
        username: String,
        state: String,
        detail: String,
        dimension: String,
        x: f64,
        y: f64,
        z: f64,
        view_distance: i32,
        chunks_loaded: u32,
        packets_seen: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_bot_status for super::RemoteReducers {
    fn set_bot_status_then(
        &self,
        server_addr: String,
        username: String,
        state: String,
        detail: String,
        dimension: String,
        x: f64,
        y: f64,
        z: f64,
        view_distance: i32,
        chunks_loaded: u32,
        packets_seen: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetBotStatusArgs {
                server_addr,
                username,
                state,
                detail,
                dimension,
                x,
                y,
                z,
                view_distance,
                chunks_loaded,
                packets_seen,
            },
            callback,
        )
    }
}
