// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetEntityEquipmentArgs {
    pub id: i32,
    pub equipment: String,
}

impl From<SetEntityEquipmentArgs> for super::Reducer {
    fn from(args: SetEntityEquipmentArgs) -> Self {
        Self::SetEntityEquipment {
            id: args.id,
            equipment: args.equipment,
        }
    }
}

impl __sdk::InModule for SetEntityEquipmentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_entity_equipment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_entity_equipment {
    /// Request that the remote module invoke the reducer `set_entity_equipment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_entity_equipment:set_entity_equipment_then`] to run a callback after the reducer completes.
    fn set_entity_equipment(&self, id: i32, equipment: String) -> __sdk::Result<()> {
        self.set_entity_equipment_then(id, equipment, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_entity_equipment` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_entity_equipment_then(
        &self,
        id: i32,
        equipment: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_entity_equipment for super::RemoteReducers {
    fn set_entity_equipment_then(
        &self,
        id: i32,
        equipment: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetEntityEquipmentArgs { id, equipment }, callback)
    }
}
