// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetEntityNameArgs {
    pub id: i32,
    pub custom_name: Option<String>,
}

impl From<SetEntityNameArgs> for super::Reducer {
    fn from(args: SetEntityNameArgs) -> Self {
        Self::SetEntityName {
            id: args.id,
            custom_name: args.custom_name,
        }
    }
}

impl __sdk::InModule for SetEntityNameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_entity_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_entity_name {
    /// Request that the remote module invoke the reducer `set_entity_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_entity_name:set_entity_name_then`] to run a callback after the reducer completes.
    fn set_entity_name(&self, id: i32, custom_name: Option<String>) -> __sdk::Result<()> {
        self.set_entity_name_then(id, custom_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_entity_name` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_entity_name_then(
        &self,
        id: i32,
        custom_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_entity_name for super::RemoteReducers {
    fn set_entity_name_then(
        &self,
        id: i32,
        custom_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetEntityNameArgs { id, custom_name }, callback)
    }
}
