// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::block_state_def_type::BlockStateDef;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetBlockStatesArgs {
    pub defs: Vec<BlockStateDef>,
}

impl From<SetBlockStatesArgs> for super::Reducer {
    fn from(args: SetBlockStatesArgs) -> Self {
        Self::SetBlockStates { defs: args.defs }
    }
}

impl __sdk::InModule for SetBlockStatesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_block_states`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_block_states {
    /// Request that the remote module invoke the reducer `set_block_states` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_block_states:set_block_states_then`] to run a callback after the reducer completes.
    fn set_block_states(&self, defs: Vec<BlockStateDef>) -> __sdk::Result<()> {
        self.set_block_states_then(defs, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_block_states` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_block_states_then(
        &self,
        defs: Vec<BlockStateDef>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_block_states for super::RemoteReducers {
    fn set_block_states_then(
        &self,
        defs: Vec<BlockStateDef>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetBlockStatesArgs { defs }, callback)
    }
}
