// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetTimeArgs {
    pub dimension: String,
    pub game_time: i64,
    pub day_time: i64,
}

impl From<SetTimeArgs> for super::Reducer {
    fn from(args: SetTimeArgs) -> Self {
        Self::SetTime {
            dimension: args.dimension,
            game_time: args.game_time,
            day_time: args.day_time,
        }
    }
}

impl __sdk::InModule for SetTimeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_time`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_time {
    /// Request that the remote module invoke the reducer `set_time` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_time:set_time_then`] to run a callback after the reducer completes.
    fn set_time(&self, dimension: String, game_time: i64, day_time: i64) -> __sdk::Result<()> {
        self.set_time_then(dimension, game_time, day_time, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_time` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_time_then(
        &self,
        dimension: String,
        game_time: i64,
        day_time: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_time for super::RemoteReducers {
    fn set_time_then(
        &self,
        dimension: String,
        game_time: i64,
        day_time: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetTimeArgs {
                dimension,
                game_time,
                day_time,
            },
            callback,
        )
    }
}
