// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetEntityAppearanceArgs {
    pub id: i32,
    pub appearance: String,
}

impl From<SetEntityAppearanceArgs> for super::Reducer {
    fn from(args: SetEntityAppearanceArgs) -> Self {
        Self::SetEntityAppearance {
            id: args.id,
            appearance: args.appearance,
        }
    }
}

impl __sdk::InModule for SetEntityAppearanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_entity_appearance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_entity_appearance {
    /// Request that the remote module invoke the reducer `set_entity_appearance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_entity_appearance:set_entity_appearance_then`] to run a callback after the reducer completes.
    fn set_entity_appearance(&self, id: i32, appearance: String) -> __sdk::Result<()> {
        self.set_entity_appearance_then(id, appearance, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_entity_appearance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_entity_appearance_then(
        &self,
        id: i32,
        appearance: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_entity_appearance for super::RemoteReducers {
    fn set_entity_appearance_then(
        &self,
        id: i32,
        appearance: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetEntityAppearanceArgs { id, appearance }, callback)
    }
}
