// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetContainerSlotArgs {
    pub window_id: i32,
    pub slot: i32,
    pub stack: String,
    pub state_id: i32,
}

impl From<SetContainerSlotArgs> for super::Reducer {
    fn from(args: SetContainerSlotArgs) -> Self {
        Self::SetContainerSlot {
            window_id: args.window_id,
            slot: args.slot,
            stack: args.stack,
            state_id: args.state_id,
        }
    }
}

impl __sdk::InModule for SetContainerSlotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_container_slot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_container_slot {
    /// Request that the remote module invoke the reducer `set_container_slot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_container_slot:set_container_slot_then`] to run a callback after the reducer completes.
    fn set_container_slot(
        &self,
        window_id: i32,
        slot: i32,
        stack: String,
        state_id: i32,
    ) -> __sdk::Result<()> {
        self.set_container_slot_then(window_id, slot, stack, state_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_container_slot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_container_slot_then(
        &self,
        window_id: i32,
        slot: i32,
        stack: String,
        state_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_container_slot for super::RemoteReducers {
    fn set_container_slot_then(
        &self,
        window_id: i32,
        slot: i32,
        stack: String,
        state_id: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetContainerSlotArgs {
                window_id,
                slot,
                stack,
                state_id,
            },
            callback,
        )
    }
}
