// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnloadChunkArgs {
    pub cx: i32,
    pub cz: i32,
}

impl From<UnloadChunkArgs> for super::Reducer {
    fn from(args: UnloadChunkArgs) -> Self {
        Self::UnloadChunk {
            cx: args.cx,
            cz: args.cz,
        }
    }
}

impl __sdk::InModule for UnloadChunkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unload_chunk`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unload_chunk {
    /// Request that the remote module invoke the reducer `unload_chunk` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unload_chunk:unload_chunk_then`] to run a callback after the reducer completes.
    fn unload_chunk(&self, cx: i32, cz: i32) -> __sdk::Result<()> {
        self.unload_chunk_then(cx, cz, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unload_chunk` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unload_chunk_then(
        &self,
        cx: i32,
        cz: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl unload_chunk for super::RemoteReducers {
    fn unload_chunk_then(
        &self,
        cx: i32,
        cz: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UnloadChunkArgs { cx, cz }, callback)
    }
}
