// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::block_change_data_type::BlockChangeData;
use super::section_data_type::SectionData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSectionsArgs {
    pub cx: i32,
    pub cz: i32,
    pub sections: Vec<SectionData>,
    pub changes: Vec<BlockChangeData>,
}

impl From<UpdateSectionsArgs> for super::Reducer {
    fn from(args: UpdateSectionsArgs) -> Self {
        Self::UpdateSections {
            cx: args.cx,
            cz: args.cz,
            sections: args.sections,
            changes: args.changes,
        }
    }
}

impl __sdk::InModule for UpdateSectionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_sections`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_sections {
    /// Request that the remote module invoke the reducer `update_sections` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_sections:update_sections_then`] to run a callback after the reducer completes.
    fn update_sections(
        &self,
        cx: i32,
        cz: i32,
        sections: Vec<SectionData>,
        changes: Vec<BlockChangeData>,
    ) -> __sdk::Result<()> {
        self.update_sections_then(cx, cz, sections, changes, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_sections` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_sections_then(
        &self,
        cx: i32,
        cz: i32,
        sections: Vec<SectionData>,
        changes: Vec<BlockChangeData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_sections for super::RemoteReducers {
    fn update_sections_then(
        &self,
        cx: i32,
        cz: i32,
        sections: Vec<SectionData>,
        changes: Vec<BlockChangeData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateSectionsArgs {
                cx,
                cz,
                sections,
                changes,
            },
            callback,
        )
    }
}
