// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::light_data_type::LightData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateLightArgs {
    pub cx: i32,
    pub cz: i32,
    pub sections: Vec<LightData>,
}

impl From<UpdateLightArgs> for super::Reducer {
    fn from(args: UpdateLightArgs) -> Self {
        Self::UpdateLight {
            cx: args.cx,
            cz: args.cz,
            sections: args.sections,
        }
    }
}

impl __sdk::InModule for UpdateLightArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_light`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_light {
    /// Request that the remote module invoke the reducer `update_light` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_light:update_light_then`] to run a callback after the reducer completes.
    fn update_light(&self, cx: i32, cz: i32, sections: Vec<LightData>) -> __sdk::Result<()> {
        self.update_light_then(cx, cz, sections, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_light` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_light_then(
        &self,
        cx: i32,
        cz: i32,
        sections: Vec<LightData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_light for super::RemoteReducers {
    fn update_light_then(
        &self,
        cx: i32,
        cz: i32,
        sections: Vec<LightData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateLightArgs { cx, cz, sections }, callback)
    }
}
