// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::monitor_data_type::MonitorData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateMonitorsArgs {
    pub items: Vec<MonitorData>,
}

impl From<UpdateMonitorsArgs> for super::Reducer {
    fn from(args: UpdateMonitorsArgs) -> Self {
        Self::UpdateMonitors { items: args.items }
    }
}

impl __sdk::InModule for UpdateMonitorsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_monitors`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_monitors {
    /// Request that the remote module invoke the reducer `update_monitors` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_monitors:update_monitors_then`] to run a callback after the reducer completes.
    fn update_monitors(&self, items: Vec<MonitorData>) -> __sdk::Result<()> {
        self.update_monitors_then(items, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_monitors` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_monitors_then(
        &self,
        items: Vec<MonitorData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_monitors for super::RemoteReducers {
    fn update_monitors_then(
        &self,
        items: Vec<MonitorData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateMonitorsArgs { items }, callback)
    }
}
