// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::block_entity_data_type::BlockEntityData;
use super::section_data_type::SectionData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertChunkArgs {
    pub dimension: String,
    pub cx: i32,
    pub cz: i32,
    pub min_section: i32,
    pub sections: Vec<SectionData>,
    pub block_entities: Vec<BlockEntityData>,
}

impl From<UpsertChunkArgs> for super::Reducer {
    fn from(args: UpsertChunkArgs) -> Self {
        Self::UpsertChunk {
            dimension: args.dimension,
            cx: args.cx,
            cz: args.cz,
            min_section: args.min_section,
            sections: args.sections,
            block_entities: args.block_entities,
        }
    }
}

impl __sdk::InModule for UpsertChunkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_chunk`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_chunk {
    /// Request that the remote module invoke the reducer `upsert_chunk` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_chunk:upsert_chunk_then`] to run a callback after the reducer completes.
    fn upsert_chunk(
        &self,
        dimension: String,
        cx: i32,
        cz: i32,
        min_section: i32,
        sections: Vec<SectionData>,
        block_entities: Vec<BlockEntityData>,
    ) -> __sdk::Result<()> {
        self.upsert_chunk_then(
            dimension,
            cx,
            cz,
            min_section,
            sections,
            block_entities,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_chunk` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_chunk_then(
        &self,
        dimension: String,
        cx: i32,
        cz: i32,
        min_section: i32,
        sections: Vec<SectionData>,
        block_entities: Vec<BlockEntityData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_chunk for super::RemoteReducers {
    fn upsert_chunk_then(
        &self,
        dimension: String,
        cx: i32,
        cz: i32,
        min_section: i32,
        sections: Vec<SectionData>,
        block_entities: Vec<BlockEntityData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertChunkArgs {
                dimension,
                cx,
                cz,
                min_section,
                sections,
                block_entities,
            },
            callback,
        )
    }
}
