// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::container_data_type::ContainerData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertContainerArgs {
    pub c: ContainerData,
}

impl From<UpsertContainerArgs> for super::Reducer {
    fn from(args: UpsertContainerArgs) -> Self {
        Self::UpsertContainer { c: args.c }
    }
}

impl __sdk::InModule for UpsertContainerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_container`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_container {
    /// Request that the remote module invoke the reducer `upsert_container` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_container:upsert_container_then`] to run a callback after the reducer completes.
    fn upsert_container(&self, c: ContainerData) -> __sdk::Result<()> {
        self.upsert_container_then(c, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_container` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_container_then(
        &self,
        c: ContainerData,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_container for super::RemoteReducers {
    fn upsert_container_then(
        &self,
        c: ContainerData,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertContainerArgs { c }, callback)
    }
}
