// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::block_entity_data_type::BlockEntityData;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertBlockEntitiesArgs {
    pub items: Vec<BlockEntityData>,
}

impl From<UpsertBlockEntitiesArgs> for super::Reducer {
    fn from(args: UpsertBlockEntitiesArgs) -> Self {
        Self::UpsertBlockEntities { items: args.items }
    }
}

impl __sdk::InModule for UpsertBlockEntitiesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_block_entities`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_block_entities {
    /// Request that the remote module invoke the reducer `upsert_block_entities` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_block_entities:upsert_block_entities_then`] to run a callback after the reducer completes.
    fn upsert_block_entities(&self, items: Vec<BlockEntityData>) -> __sdk::Result<()> {
        self.upsert_block_entities_then(items, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_block_entities` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_block_entities_then(
        &self,
        items: Vec<BlockEntityData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_block_entities for super::RemoteReducers {
    fn upsert_block_entities_then(
        &self,
        items: Vec<BlockEntityData>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertBlockEntitiesArgs { items }, callback)
    }
}
