// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_time_type::WorldTime;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_time`.
///
/// Obtain a handle from the [`WorldTimeTableAccess::world_time`] method on [`super::RemoteTables`],
/// like `ctx.db.world_time()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_time().on_insert(...)`.
pub struct WorldTimeTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldTime>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `world_time`.
pub struct WorldTimeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WorldTimeTableAccessor {
    type Row = WorldTime;
    type Handle<'db> = WorldTimeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.world_time()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_time`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldTimeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldTimeTableHandle`], which mediates access to the table `world_time`.
    fn world_time(&self) -> WorldTimeTableHandle<'_>;
}

impl WorldTimeTableAccess for super::RemoteTables {
    fn world_time(&self) -> WorldTimeTableHandle<'_> {
        WorldTimeTableHandle {
            imp: self.imp.get_table::<WorldTime>("world_time"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldTimeInsertCallbackId(__sdk::CallbackId);
pub struct WorldTimeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WorldTimeTableHandle<'ctx> {
    type Row = WorldTime;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldTime> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for WorldTimeTableHandle<'ctx> {
    type Row = WorldTime;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldTime> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldTimeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldTimeInsertCallbackId {
        WorldTimeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldTimeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldTimeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldTimeDeleteCallbackId {
        WorldTimeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldTimeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WorldTimeTableHandle<'ctx> {
    type InsertCallbackId = WorldTimeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldTimeInsertCallbackId {
        WorldTimeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldTimeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WorldTimeTableHandle<'ctx> {
    type DeleteCallbackId = WorldTimeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldTimeDeleteCallbackId {
        WorldTimeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldTimeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldTimeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldTimeTableHandle<'ctx> {
    type UpdateCallbackId = WorldTimeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldTimeUpdateCallbackId {
        WorldTimeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldTimeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WorldTimeTableHandle<'ctx> {
    type UpdateCallbackId = WorldTimeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldTimeUpdateCallbackId {
        WorldTimeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldTimeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `dimension` unique index on the table `world_time`,
/// which allows point queries on the field of the same name
/// via the [`WorldTimeDimensionUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_time().dimension().find(...)`.
pub struct WorldTimeDimensionUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldTime, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldTimeTableHandle<'ctx> {
    /// Get a handle on the `dimension` unique index on the table `world_time`.
    pub fn dimension(&self) -> WorldTimeDimensionUnique<'ctx> {
        WorldTimeDimensionUnique {
            imp: self.imp.get_unique_constraint::<String>("dimension"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldTimeDimensionUnique<'ctx> {
    /// Find the subscribed row whose `dimension` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<WorldTime> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldTime>("world_time");
    _table.add_unique_constraint::<String>("dimension", |row| &row.dimension);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldTime>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldTime>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldTime`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_timeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldTime`.
    fn world_time(&self) -> __sdk::__query_builder::Table<WorldTime>;
}

impl world_timeQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_time(&self) -> __sdk::__query_builder::Table<WorldTime> {
        __sdk::__query_builder::Table::new("world_time")
    }
}
