// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldTime {
    pub dimension: String,
    pub game_time: i64,
    pub day_time: i64,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for WorldTime {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldTime`.
///
/// Provides typed access to columns for query building.
pub struct WorldTimeCols {
    pub dimension: __sdk::__query_builder::Col<WorldTime, String>,
    pub game_time: __sdk::__query_builder::Col<WorldTime, i64>,
    pub day_time: __sdk::__query_builder::Col<WorldTime, i64>,
    pub updated_at: __sdk::__query_builder::Col<WorldTime, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for WorldTime {
    type Cols = WorldTimeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldTimeCols {
            dimension: __sdk::__query_builder::Col::new(table_name, "dimension"),
            game_time: __sdk::__query_builder::Col::new(table_name, "game_time"),
            day_time: __sdk::__query_builder::Col::new(table_name, "day_time"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldTime`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldTimeIxCols {
    pub dimension: __sdk::__query_builder::IxCol<WorldTime, String>,
}

impl __sdk::__query_builder::HasIxCols for WorldTime {
    type IxCols = WorldTimeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldTimeIxCols {
            dimension: __sdk::__query_builder::IxCol::new(table_name, "dimension"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldTime {}
